MODULE M_COM_STOC
  IMPLICIT NONE
!----------------------------------------
!     STOC との通信用
!----------------------------------------
!
      INTEGER,PARAMETER::MAXPE=256
      INTEGER::NSIZEALL,NSIZE,NRANK
      INTEGER::IDCON(7),IPECON(8,MAXPE),IDTABL(2,MAXPE)
      INTEGER::NUMPE(2,0:MAXPE),NUMCOM(5,MAXPE)
      CHARACTER(LEN=64)::NMFILE(MAXPE)
!
      INTEGER::IB_SD(MAXPE)
      INTEGER::NP_STOC,IP_STOC(MAXPE),IP_STOC_MAIN
      INTEGER::IA_STOC(MAXPE)
      INTEGER::NC_STOC,IC_STOC(2,MAXPE)
END MODULE M_COM_STOC
