      SUBROUTINE PCNSTR(DPG,NNOD,INDOP0,IPND,PPND,PG2)

      IMPLICIT REAL*8 (A-H,O-Z)
      DIMENSION DPG(NNOD),INDOP0(NNOD),PPND(NNOD),PG2(NNOD),IPND(NNOD)

      DO I = 1, NNOD
        IF( INDOP0(I) == 0 .AND. IPND(I) == 1 ) 
     &    DPG(I) = PPND(I) - PG2(I)
      ENDDO

      END
