      SUBROUTINE SF_ALLOC0()

      USE VF_A2ARRAY

      IMPLICIT REAL*8(A-H,O-Z)

      INCLUDE 'VF_A0PRM.h'
      INCLUDE 'VF_ANUMBI.h'

      IERR = 0
      ALLOCATE(GGV_0(NUMI,NUMJ,NUMK),STAT=IERR)
      ALLOCATE(GGX_0(NUMI,NUMJ,NUMK),STAT=IERR)
      ALLOCATE(GGY_0(NUMI,NUMJ,NUMK),STAT=IERR)
      ALLOCATE(GGZ_0(NUMI,NUMJ,NUMK),STAT=IERR)
      ALLOCATE(INDX0(NUMI,NUMJ,NUMK),STAT=IERR)
      ALLOCATE(INDY0(NUMI,NUMJ,NUMK),STAT=IERR)
      ALLOCATE(INDZ0(NUMI,NUMJ,NUMK),STAT=IERR)
      IF (IERR.NE.0) CALL VF_A2ERR('SF_ALLOC0','CAN NOT ALLOC.')
      GGV_0 = GGV
      GGX_0 = GGX
      GGY_0 = GGY
      GGZ_0 = GGZ
      INDX0 = INDX
      INDY0 = INDY
      INDZ0 = INDZ

      IERR = 0
      ALLOCATE(BCU0  (NUMB,3    ),STAT=IERR)
      ALLOCATE(BCV0  (NUMB,3    ),STAT=IERR)
      ALLOCATE(BCW0  (NUMB,3    ),STAT=IERR)
      ALLOCATE(BCP0  (NUMB,3    ),STAT=IERR)
      ALLOCATE(BCF0  (NUMB      ),STAT=IERR)
      ALLOCATE(BCVI0 (NUMB      ),STAT=IERR)
      IF (LEQK.NE.0) THEN
        ALLOCATE(BCK0 (  NUMB,3 ),STAT=IERR)
        ALLOCATE(BCE0 (  NUMB,3 ),STAT=IERR)
      ENDIF
      IF (LEQT.NE.0) THEN
        ALLOCATE(BCT0 (  NUMB   ),STAT=IERR)
        ALLOCATE(BCTI0(2,NUMB   ),STAT=IERR)
      ENDIF
      IF (LEQC.GT.0) THEN
        ALLOCATE(BCC0 (  NUMB,LEQC),STAT=IERR)
        ALLOCATE(BCCI0(2,NUMB,LEQC),STAT=IERR)
      ENDIF
      ALLOCATE(INDB0(MAXB1,NUMB),STAT=IERR)
      IF (LEQK.NE.0) THEN
        ALLOCATE(INDBK0(MAXBK1,NUMB),STAT=IERR)
        ALLOCATE(INDBE0(MAXBE1,NUMB),STAT=IERR)
      ENDIF
      IF (LEQT.NE.0) THEN
        ALLOCATE(INDBT0(NUMB     ),STAT=IERR)
      ENDIF
      IF (LEQC.GT.0) THEN
        ALLOCATE(INDBC0(NUMB,LEQC),STAT=IERR)
      ENDIF
      IF (IERR.NE.0) CALL VF_A2ERR('SF_ALLOC0','CAN NOT ALLOC.')
      BCU0 = BCU
      BCV0 = BCV
      BCW0 = BCW
      BCP0 = BCP
      BCF0 = BCF
      BCVI0= BCVI
      IF (LEQK.NE.0) THEN
        BCK0 = BCK
        BCE0 = BCE
      ENDIF
      IF (LEQT.NE.0) THEN
        BCT0 = BCT
        BCTI0= BCTI
      ENDIF
      IF (LEQC.GT.0) THEN
        BCC0 = BCC
        BCCI0= BCCI
      ENDIF
      INDB0 = INDB
      IF (LEQK.NE.0) THEN
        INDBK0 = INDBK
        INDBE0 = INDBE
      ENDIF
      IF (LEQT.NE.0) THEN
        INDBT0 = INDBT
      ENDIF
      IF (LEQC.GT.0) THEN
        INDBC0 = INDBC
      ENDIF

      END