      SUBROUTINE SF_COMM_I_1(IRECV,ISEND,IPE,NPE)

      IMPLICIT REAL*8(A-H,O-Z)

      DIMENSION IRECV(NPE),IPE(NPE),IREQ1(NPE),IREQ2(NPE)

      DO I = 1, NPE
        CALL SF_MPI_ISEND_I(ISEND,1,IPE(I),IREQ1(I))
      ENDDO

      DO I = 1, NPE
        CALL SF_MPI_IRECV_I(IRECV(I),1,IPE(I),IREQ2(I))
      ENDDO

      CALL SF_MPI_WAITALL(NPE,IREQ1)
      CALL SF_MPI_WAITALL(NPE,IREQ2)

      END
