      SUBROUTINE SF_POS_INIT(POS,POS2,DVEL,DVEL2,POS0,POS20,DVEL20
     &                      ,IPND0,PRES0,IPFACE0,AFC,IPGRID,IPGRID0
     &                      ,IRFACE,IRGRID0,IGNO,IENO,ZZ,NF,PP,DZ)

      IMPLICIT REAL*8(A-H,O-Z)

      INCLUDE 'VF_A0PRM.h'
      INCLUDE 'VF_ANUMBI.h'
      INCLUDE 'VF_APARAI.h'
      INCLUDE 'VF_APHYSR.h'
      INCLUDE 'SF_STRUCT.h'

      DIMENSION POS(3,NNOD),POS2(3,NNOD),POS0(3,NNOD0),POS20(3,NNOD0)
     &         ,DVEL(3,NELM),DVEL2(3,NELM),DVEL20(3,NELM0),IGNO(NNOD)
     &         ,IENO(NELM),IPND0(NNOD0),IPGRID(2,NNOD),IPGRID0(2,NNOD0)
     &         ,PRES0(NNOD0),PP(NUMI,NUMJ,NUMK),ZZ(MAXG1,NUMK)
     &         ,NF(NUMI,NUMJ,NUMK),IPFACE0(12,NPFC0),AFC(NPFC0)
     &         ,IRFACE(NPFC0),IRGRID0(NNOD0),DZ(NUMI,NUMJ)

      INTEGER, POINTER :: IPF(:,:)

      IF( MYRANK == 0 ) CALL SF_GIPND(IPND0,IPGRID0,NNOD0)

      CALL SF_GPRES(PRES0,PP,IPGRID,IGNO,POS,ZZ,NF)

      IF( ISTM == 1 ) DZ(:,:) = 0.D0

      IF( MYRANK == 0 ) THEN

        CALL SF_C_MPI_SEND_D(WVLVL,1,IROOTS)
        CALL SF_C_MPI_SEND_D(ZZ(1,NUMK),1,IROOTS)

        ALLOCATE( IPF(10,NPFC0) )

        IPF(:,:) = 0
        IPF(:,:) = IPFACE0(3:12,:)
   
        CALL SF_C_MPI_SEND_I(NPFC0,1,IROOTS)
        CALL SF_C_MPI_SEND_I(IPF,NPFC0*10,IROOTS)

        DEALLOCATE( IPF )

        CALL SF_C_MPI_SEND_D(AFC,NPFC0,IROOTS)
        CALL SF_C_MPI_SEND_I(IPND0,NNOD0,IROOTS)

        IF( ISTM == 1 ) THEN
          CALL SF_C_MPI_SEND_I(IRFACE,NPFC0,IROOTS)
          CALL SF_C_MPI_SEND_I(IRGRID0,NNOD0,IROOTS)
        ENDIF

        CALL SF_C_MPI_SEND_D(PRES0,NNOD0,IROOTS)

        TNEXT = 0.D0
        CALL SF_C_MPI_SEND_D(TNEXT,1,IROOTS)

        CALL SF_C_MPI_RECV_D(POS20,NNOD0*3,IROOTS)
        IF( IGEO == 1 ) CALL SF_C_MPI_RECV_D(DVEL20,NELM0*3,IROOTS)

      ENDIF

      IF( IPART == 0 ) THEN

        IF( MYRANK == 0 ) THEN
          POS2 = POS20
          DVEL2 = DVEL20
        ENDIF

        CALL VF_P1BCSD(POS2,NNOD*3,0)
        CALL VF_P1BCSD(DVEL2,NELM*3,0)

      ELSEIF( IPART == 1 ) THEN

        CALL SF_BCAST_D(POS2,IGNO,NNOD,POS20,NNOD0,3)
        CALL SF_BCAST_D(DVEL2,IENO,NELM,DVEL20,NELM0,3)

      ENDIF

      TSTR2 = 0.D0

      IF( MYRANK == 0 ) POS0 = POS20

      POS = POS2
      DVEL = DVEL2

      END
