      SUBROUTINE SF_PRSINI(IPFACE0,AFC,IPGRID0,IPND0,ZZ)

      IMPLICIT REAL*8(A-H,O-Z)

      INCLUDE 'VF_A0PRM.h'
      INCLUDE 'VF_AFILEI.h'
      INCLUDE 'VF_ANUMBI.h'
      INCLUDE 'VF_APARAI.h'
      INCLUDE 'VF_APHYSR.h'
      INCLUDE 'SF_STRUCT.h'

      DIMENSION IPFACE0(12,NPFC0),IPGRID0(2,NNOD0),IPND0(NNOD0)
     &         ,AFC(NPFC0),ZZ(MAXG1,NUMK)

      IF( MYRANK /= 0 ) RETURN

      OPEN(MFILTP,FILE='data.prs',IOSTAT=IERR)
      IF( IERR > 0 ) 
     &    CALL VF_A2ERR('SF_PRSINI','CAN NOT OPEN (data.prs).')
      ITPFIL = MFILTP

      WRITE(ITPFIL,'(1P2E15.7)') WVLVL,ZZ(1,NUMK)

      WRITE(ITPFIL,'(I10)') NPFC0

      DO I = 1, NPFC0
        WRITE(ITPFIL,'(10I10)') IPFACE0(3:12,I)
      ENDDO

      DO I = 1, NPFC0
        WRITE(ITPFIL,'(1PE15.7)') AFC(I)
      ENDDO

      CALL SF_GIPND(IPND0,IPGRID0,NNOD0)

      DO I = 1, NNOD0
        WRITE(ITPFIL,'(I1)') IPND0(I)
      ENDDO

      END
