      SUBROUTINE SF_REALLOC(NELM,NNOD,NPFC)

      USE VF_A2ARRAY
      USE SF_ARRAY

      IMPLICIT REAL*8(A-H,O-Z)

      DEALLOCATE( IELM )
      DEALLOCATE( IENO )
      DEALLOCATE( INDG )
      DEALLOCATE( IGFC )
      DEALLOCATE( GRDL )
      DEALLOCATE( IGNO )
      DEALLOCATE( IPFACE )
      DEALLOCATE( IPFNO )
      DEALLOCATE( IPGRID )
      DEALLOCATE( POS )
      DEALLOCATE( POS1 )
      DEALLOCATE( POS2 )
      DEALLOCATE( DVEL )
      DEALLOCATE( DVEL1 )
      DEALLOCATE( DVEL2 )
      DEALLOCATE( SPC )

      ALLOCATE( IELM(24,NELM) )
      ALLOCATE( IENO(NELM) )
      ALLOCATE( INDG(NNOD) )
      ALLOCATE( IGFC(NNOD) )
      ALLOCATE( GRDL(NNOD) )
      ALLOCATE( IGNO(NNOD) )
      ALLOCATE( IPFACE(12,NPFC) )
      ALLOCATE( IPFNO(NPFC) )
      ALLOCATE( IPGRID(2,NNOD) )
      ALLOCATE( POS(3,NNOD) )
      ALLOCATE( POS1(3,NNOD) )
      ALLOCATE( POS2(3,NNOD) )
      ALLOCATE( DVEL(3,NELM) )
      ALLOCATE( DVEL1(3,NELM) )
      ALLOCATE( DVEL2(3,NELM) )
      ALLOCATE( SPC(NELM) )

      END
