      SUBROUTINE SF_STR_OBST(GGV,GGX,GGY,GGZ,GGW,GGR,GLV,GLX,GLY,GLZ,NF
     &                      ,INDC,INDX,INDY,INDZ,SPC,LNDC_0,LNDC0,LNDC
     &                      ,KST,GGV_0,GGX_0,GGY_0,GGZ_0,XX,YY,ZZ,CM0
     &                      ,SUMZ,IELM,POS,POR,MODE,WK01,WK02,WK03,WK04
     &                      ,WK05,WK06,WK07,WK08,WK09,WK10,WK11,WK12
     &                      ,WK13,DBUF,NFP,INDXP,INDYP,INDZP,GGXP,GGYP
     &                      ,GGZP)

      USE SF_TYPE

      IMPLICIT REAL*8(A-H,O-Z)

      INCLUDE 'VF_A0PRM.h'
      INCLUDE 'VF_ANUMBI.h'
      INCLUDE 'VF_APARAI.h'
      INCLUDE 'SF_STRUCT.h'

      TYPE(SPACE) :: SPC(NELM)

      DIMENSION GGV(NUMI,NUMJ,NUMK),GGX(NUMI,NUMJ,NUMK)
     &         ,GGY(NUMI,NUMJ,NUMK),GGZ(NUMI,NUMJ,NUMK)
     &         ,GGW(NUMI,NUMJ,NUMK),GGR(NUMI,NUMJ,NUMK)
     &         ,GGV_0(NUMI,NUMJ,NUMK),GGX_0(NUMI,NUMJ,NUMK)
     &         ,GGY_0(NUMI,NUMJ,NUMK),GGZ_0(NUMI,NUMJ,NUMK)
     &         ,XX(MAXG1,NUMI),YY(MAXG1,NUMJ),ZZ(MAXG1,NUMK)
     &         ,WK01(NUMI,NUMJ,NUMK),WK02(NUMI,NUMJ,NUMK)
     &         ,WK03(NUMI,NUMJ,NUMK),WK04(NUMI,NUMJ,NUMK)
     &         ,WK05(NUMI,NUMJ,NUMK),WK06(NUMI,NUMJ,NUMK)
     &         ,WK07(NUMI,NUMJ,NUMK),WK08(NUMI,NUMJ,NUMK)
     &         ,WK09(NUMI,NUMJ,NUMK),WK10(NUMI,NUMJ,NUMK)
     &         ,WK11(NUMI,NUMJ,NUMK),WK12(NUMI,NUMJ,NUMK)
     &         ,WK13(NUMI,NUMJ,NUMK)
     &         ,INDX(NUMI,NUMJ,NUMK),INDY(NUMI,NUMJ,NUMK)
     &         ,INDZ(NUMI,NUMJ,NUMK),NF(NUMI,NUMJ,NUMK)
     &         ,GLV(NUMI,NUMJ,NUMK),GLX(NUMI,NUMJ,NUMK)
     &         ,GLY(NUMI,NUMJ,NUMK),GLZ(NUMI,NUMJ,NUMK)
     &         ,DBUF(NUMBUF*MAXBUF),IELM(24,NELM),POS(3,NNOD)
     &         ,POR(NELM),CM0(NUMI,NUMJ,NUMK),INDC(NUMI,NUMJ,NUMK)
     &         ,INDXP(NUMI,NUMJ,NUMK),INDYP(NUMI,NUMJ,NUMK)
     &         ,INDZP(NUMI,NUMJ,NUMK),NFP(NUMI,NUMJ,NUMK)
     &         ,GGXP(NUMI,NUMJ,NUMK),GGYP(NUMI,NUMJ,NUMK)
     &         ,GGZP(NUMI,NUMJ,NUMK),LNDC(NUMI,NUMJ),LNDC0(NUMI,NUMJ)
     &         ,LNDC_0(NUMI,NUMJ),KST(NUMI,NUMJ),SUMZ(NUMI,NUMJ)

      NFP = NF

      INDXP = INDX
      INDYP = INDY
      INDZP = INDZ

      GGXP = GGX
      GGYP = GGY
      GGZP = GGZ

      GGV = GGV_0
      GGX = GGX_0
      GGY = GGY_0
      GGZ = GGZ_0
      GGW = GGV_0

      LNDC0 = LNDC

      CALL SF_MDPORO(GGV,GGX,GGY,GGZ,GGW,GGR,SPC,LNDC_0,LNDC,KST,XX,YY
     &              ,ZZ,GGV_0,NF,SUMZ,IELM,POS,POR,MODE,WK01,WK02,WK03
     &              ,WK04,WK05,WK06,WK07,WK08,WK09,WK10,WK11,WK12,WK13
     &              ,DBUF)

      CALL SF_NF_RESET(NF,INDC,GGV,WK01,DBUF)

      CALL SF_INDX_RESET(INDX,INDY,INDZ,NF,GGX,GGY,GGZ)

      CALL VF_CGLV(CM0,GGV,GLV,NF)
      
      CALL VF_CGLXYZ(XX,YY,ZZ,CM0,GGX,GGY,GGZ,GLX,GLY,GLZ,DBUF,NF,INDX
     &              ,INDY,INDZ)
      
      END
