      SUBROUTINE SF_STR0()

      USE VF_A2ARRAY
      USE SF_ARRAY

      IMPLICIT REAL*8(A-H,O-Z)

      INCLUDE 'SF_STRUCT.h'

      IF(ICPL.EQ.2) CALL SF_SEND_RST()
      CALL SF_RD_OBST()
      CALL SF_PFACE0()
      IF( ISTM == 1 ) CALL SF_RFACE0()
      CALL SF_BCS_OBST()
      IF(ICPL.EQ.2) CALL SF_RECV_CONT()
      CALL SF_ALLOC0()
      CALL SF_PFACE1()
      CALL SF_PFACE3()
      CALL SF_STR_OBST(GGV,GGX,GGY,GGZ,GGW,GGR,GLV,GLX,GLY,GLZ,NF,INDC
     &                ,INDX,INDY,INDZ,SPC,LNDC_0,LNDC0,LNDC,KST,GGV_0
     &                ,GGX_0,GGY_0,GGZ_0,XX,YY,ZZ,CM0,SUMZ,IELM,POS,POR
     &                ,0,WK01,WK02,WK03,WK04,WK05,WK06,WK07,WK08,WK09
     &                ,WK10,WK11,WK12,WK13,DBUF,WK14,WK15,WK16,WK17,WK18
     &                ,WK19,WK20)
      CALL SF_PFACE2()
      CALL SF_ALLOC1()
      CALL SF_BC_RESET(INDB,INDBK,INDBE,INDBT,INDBC,BCU,BCV,BCW,BCP
     &                ,BCF,BCVI,BCK,BCE,BCT,BCTI,BCC,BCCI,GGX,GGY
     &                ,GGZ,GLX,GLY,GLZ,NF,INDX,INDY,INDZ,INDX0,INDY0
     &                ,INDZ0,INDB0,INDBK0,INDBE0,INDBT0,INDBC0,BCU0
     &                ,BCV0,BCW0,BCP0,BCF0,BCVI0,BCK0,BCE0,BCT0
     &                ,BCTI0,BCC0,BCCI0,XX,YY,ZZ,IELM,POS,DVEL)
      IF (ICPL.EQ.1) CALL SF_DEALLOC()

      END
