      SUBROUTINE SF_SEND_SURF(IPND0,IPFACE0,AFC,IPGRID0,ZZ,IRFACE
     &                       ,IRGRID0)

      IMPLICIT REAL*8(A-H,O-Z)

      INCLUDE 'VF_A0PRM.h'
      INCLUDE 'VF_ANUMBI.h'
      INCLUDE 'VF_APARAI.h'
      INCLUDE 'VF_APHYSR.h'
      INCLUDE 'SF_STRUCT.h'

      DIMENSION IPND0(NNOD0),IPGRID0(2,NNOD0),IPFACE0(12,NPFC0)
     &         ,AFC(NPFC0),ZZ(MAXG1,NUMK),IRFACE(NPFC0),IRGRID0(NNOD0)

      INTEGER, POINTER :: IPF(:,:)

      IF( MYRANK > 0 ) RETURN

      CALL SF_C_MPI_SEND_D(WVLVL,1,IROOTS)
      CALL SF_C_MPI_SEND_D(ZZ(1,NUMK),1,IROOTS)

      CALL SF_GIPND(IPND0,IPGRID0,NNOD0)

      ALLOCATE( IPF(10,NPFC0) )

      IPF(:,:) = 0
      IPF(:,:) = IPFACE0(3:12,:)
   
      CALL SF_C_MPI_SEND_I(NPFC0,1,IROOTS)
      CALL SF_C_MPI_SEND_I(IPF,NPFC0*10,IROOTS)

      DEALLOCATE( IPF )

      CALL SF_C_MPI_SEND_D(AFC,NPFC0,IROOTS)
      CALL SF_C_MPI_SEND_I(IPND0,NNOD0,IROOTS)

      IF( ISTM == 1 ) THEN
        CALL SF_C_MPI_SEND_I(IRFACE,NPFC0,IROOTS)
        CALL SF_C_MPI_SEND_I(IRGRID0,NNOD0,IROOTS)
      ENDIF

      END
