      SUBROUTINE SF_STM_FINALIZE()

      IMPLICIT REAL*8(A-H,O-Z)

      INCLUDE 'VF_A0PRM.h'
      INCLUDE 'VF_APARAI.h'
      INCLUDE 'SF_STRUCT.h'

      REAL(8), POINTER :: DRECV(:,:)

      IF( MYRANK == 0 ) THEN
        ALLOCATE( DRECV(NUMI0,NUMJ0) )
        CALL SF_STM_C_MPI_RECV_D(DRECV,NUMI0*NUMJ0,IROOTSTM)
        DEALLOCATE( DRECV )
        CALL SF_STM_C_MPI_SEND_I(1,1,IROOTSTM)
      ENDIF
      
      END
