      SUBROUTINE SF_STR2(DT,DTO)

      USE VF_A2ARRAY
      USE SF_ARRAY

      IMPLICIT REAL*8(A-H,O-Z)

      INCLUDE 'VF_ATIMER.h'
      INCLUDE 'SF_STRUCT.h'

      IF( ISTM == 1 )
     &  CALL SF_DPTH_UPDATE(DZ,SUMZ,XX,YY,ZZ,UU,VV,FF,FX,FY,GGX,GGY,GGW
     &                     ,GGR,LNDC,NF,INDX,INDY,FLFU,FLFV,DT,DTO)
      CALL SF_POS_UPDATE1(IPND0,PRES0,DELZ0,IFIX0,GRID,POS,IPGRID
     &                   ,IPGRID0,IRGRID,IELM,IGNO,XX,YY,ZZ,NF,PP,DZ
     &                   ,LNDC0,DT)
      IF( TNOW + DT > TSTR2 .AND. IPART == 1 ) CALL SF_UPDT_OBST()
      CALL SF_POS_UPDATE2(POS,POS1,POS2,DVEL,DVEL1,DVEL2,POS0,POS10
     &                   ,POS20,DVEL10,DVEL20,SPC,IPND0,PRES0,DELZ0
     &                   ,IFIX0,GRDL,IGFC,IELM,AFC,IGNO,IENO,XX,YY,ZZ
     &                   ,DT)
      CALL SF_PFACE1()
      CALL SF_PFACE3()
      CALL SF_STR_OBST(GGV,GGX,GGY,GGZ,GGW,GGR,GLV,GLX,GLY,GLZ,NF,INDC
     &                ,INDX,INDY,INDZ,SPC,LNDC_0,LNDC0,LNDC,KST,GGV_0
     &                ,GGX_0,GGY_0,GGZ_0,XX,YY,ZZ,CM0,SUMZ,IELM,POS,POR
     &                ,2,WK01,WK02,WK03,WK04,WK05,WK06,WK07,WK08,WK09
     &                ,WK10,WK11,WK12,WK13,DBUF,WK14,WK15,WK16,WK17,WK18
     &                ,WK19,WK20)
      CALL SF_PFACE2()
      IF( ISTM == 1 ) CALL SF_RFACE2()
      CALL SF_ALLOC1()
      CALL SF_BC_RESET(INDB,INDBK,INDBE,INDBT,INDBC,BCU,BCV,BCW,BCP
     &                ,BCF,BCVI,BCK,BCE,BCT,BCTI,BCC,BCCI,GGX,GGY
     &                ,GGZ,GLX,GLY,GLZ,NF,INDX,INDY,INDZ,INDX0,INDY0
     &                ,INDZ0,INDB0,INDBK0,INDBE0,INDBT0,INDBC0,BCU0
     &                ,BCV0,BCW0,BCP0,BCF0,BCVI0,BCK0,BCE0,BCT0
     &                ,BCTI0,BCC0,BCCI0,XX,YY,ZZ,IELM,POS,DVEL)
      CALL SF_CINIT(XX,YY,ZZ,UU,VV,WW,PP,FF,FX,FY,FZ,ANU,GGV,GGX,GGY
     &             ,GGZ,BCU,BCV,BCW,BCP,BCF,BCVI,DMTBTT,DMTBZZ,DMTBHH
     &             ,DMTBUN,DMTBUT,DBUF,WK01,WK02,WK03,NF,INDX,INDY
     &             ,INDZ,INDB,INDS,IBUF,WK14,WK15,WK16,WK17,WK18,WK19
     &             ,WK20)

      END
