      SUBROUTINE CLKEPS(AK,AKN,EP,EPN,UU,VV,WW,TMU,RHOW,XC,YC,ZC,
     $                  XCP,YCOS,YCOSP,HU,HV,HW,HX,HDEP,KH,
     $                  GV,GX,GY,GZ,HH,INDU,INDV,INDW,INDP,INDK,
     $                  LLWALL,LLWALP,KF,KG,KP,AKBCN,EPBCN,
     $                  FU,FV,FW,WRK4,WRK5,WRK6,GS,GT,IST0)
C======================================================================
C     高Re型k-ε乱流モデルを解く
C       FU: X方向熱流束,FV: Y方向熱流束,FW: Z方向熱流束
C       TT: 新しい時刻の温度(°C),TN:古い時刻の温度(°C)
C======================================================================
      IMPLICIT NONE
C
      INCLUDE 'DOMAIN.h'
      INCLUDE 'CP_NESTBC.h'
      INCLUDE 'TIMEI.h'
C
      REAL(8),INTENT(INOUT)::AK(MX,MY,MZ),AKN(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::EP(MX,MY,MZ),EPN(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::UU(MX,MY,MZ),VV(MX,MY,MZ),WW(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::HU(MX,MY,MZ),HV(MX,MY,MZ),HW(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::TMU(MX,MY,MZ),RHOW(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::XC(8,MX,MY),YC(8,MY),ZC(8,MZ)
      REAL(8),INTENT(IN)::XCP(8,MX,MY),YCOS(MY),YCOSP(MY)
      REAL(8),INTENT(INOUT)::GV(MX,MY,MZ),GX(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::GY(MX,MY,MZ),GZ(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::HH(MX,MY),HX(MX,MY),HDEP(MX,MY)
      INTEGER,INTENT(INOUT)::INDU(MX,MY,MZ),INDV(MX,MY,MZ)
      INTEGER,INTENT(INOUT)::INDW(MX,MY,MZ)
      INTEGER,INTENT(INOUT)::INDP(MX,MY,MZ),INDK(MX,MY,MZ)
      INTEGER,INTENT(INOUT)::LLWALL(8,MLWALL),LLWALP(8,MLWALP)
      INTEGER,INTENT(INOUT)::KF(MX,MY),KG(MX,MY),KP(MX,MY),KH(MX,MY)
      REAL(8),INTENT(INOUT)::AKBCN(NXY,MZ,4),EPBCN(NXY,MZ,4)
      REAL(8),INTENT(INOUT)::FU(MX,MY,MZ),FV(MX,MY,MZ),FW(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::WRK4(MX,MY,MZ),WRK5(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::WRK6(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::GS(MX,MY,MZ),GT(MX,MY,MZ)
      INTEGER,INTENT(INOUT)::IST0
C
C
      IF(ISTEP.EQ.IST0) THEN
        CALL WLCONT(INDK,INDP,LLWALL,LLWALP)
      END IF
C
      CALL CLKEGN(UU,VV,WW,TMU,RHOW,WRK4,WRK5,WRK6,INDU,INDV,INDW,INDP,
     $            XC,YC,ZC,KF,KP,KG,GS,GT)
C
      CALL CLKEQ(AK,AKN,EP,HU,HV,HW,TMU,GS,GT,XC,YC,ZC,XCP,YCOS,
     $           GV,GX,GY,GZ,HH,HX,HDEP,INDP,INDU,INDV,INDW,
     $           LLWALL,LLWALP,KF,KH,KG,KP,FU,FV,FW,AKBCN,WRK4,WRK5)
C
      CALL CLEEQ(EP,EPN,AKN,HU,HV,HW,TMU,GS,GT,XC,YC,ZC,XCP,YCOS,
     $           GV,GX,GY,GZ,HH,HX,HDEP,INDP,INDU,INDV,INDW,
     $           LLWALL,LLWALP,KF,KH,KG,KP,FU,FV,FW,EPBCN,WRK4,WRK5)
C
      CALL WALBND(AK,EP,UU,VV,WW,TMU,INDP,INDK,XC,YC,ZC,
     $            LLWALL,LLWALP,KF)
C
      RETURN
      END
