      SUBROUTINE CLKEQ(AK,SN,EP,HU,HV,HW,TMU,GS,GT,XC,YC,ZC,XCP,YCOS,
     $                 GV,GX,GY,GZ,HH,HX,HDEP,INDP,INDU,INDV,INDW,
     $               LLWALL,LLWALP,KF,KH,KG,KP,FU,FV,FW,AKBCN,SRCA,SRCB)
C======================================================================
C     輸送方程式を解き新しい時刻の乱流エネルギーを計算する
C       FU: X方向熱流束,FV: Y方向熱流束,FW: Z方向熱流束
C       AK: 新しい時刻のk(m**2/s**2),AKN:古い時刻のk(m**/s**2)
C======================================================================
      IMPLICIT NONE
C
      INCLUDE 'DOMAIN.h'
      INCLUDE 'MODELI.h'
      INCLUDE 'MODELR.h'
      INCLUDE 'PROPTY.h'
      INCLUDE 'TURBR.h'
      INCLUDE 'CP_NESTBC.h'
C
      REAL(8),INTENT(INOUT)::AK(MX,MY,MZ),SN(MX,MY,MZ),EP(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::HU(MX,MY,MZ),HV(MX,MY,MZ),HW(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::TMU(MX,MY,MZ),GS(MX,MY,MZ),GT(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::XC(8,MX,MY),YC(8,MY),ZC(8,MZ)
      REAL(8),INTENT(IN)::XCP(8,MX,MY),YCOS(MY)
      REAL(8),INTENT(INOUT)::GV(MX,MY,MZ),GX(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::GY(MX,MY,MZ),GZ(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::HH(MX,MY),HX(MX,MY),HDEP(MX,MY)
      INTEGER,INTENT(INOUT)::INDP(MX,MY,MZ),INDU(MX,MY,MZ)
      INTEGER,INTENT(INOUT)::INDV(MX,MY,MZ),INDW(MX,MY,MZ)
      INTEGER,INTENT(INOUT)::LLWALL(8,MLWALL),LLWALP(8,MLWALP)
      INTEGER,INTENT(INOUT)::KF(MX,MY),KG(MX,MY),KP(MX,MY),KH(MX,MY)
      REAL(8),INTENT(INOUT)::FU(MX,MY,MZ),FV(MX,MY,MZ),FW(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::AKBCN(NXY,4,MZ)
      REAL(8),INTENT(INOUT)::SRCA(MX,MY,MZ),SRCB(MX,MY,MZ)
C
      INTEGER::NN=3,IZCAL=0
      INTEGER::I,J,K,LL
C
      CALL CELLSC(AK,SN,GV,XC,YC,ZC,HX,HDEP,INDP,KH,KG)
C
      CALL FLUXSX(FU,AK,HU,TMU,GX,HDEP,HX,XC,ZC,INDP,INDU,LLWALL,
     $            KG,KP,KH,AKBCN,NN,ANUH,SGK,PARAMK)
C
      CALL FLUXSY(FV,AK,HV,TMU,GY,HDEP,HX,YC,ZC,INDP,INDV,LLWALL,
     $            KG,KP,KH,AKBCN,NN,ANUH,SGK,PARAMK)
C
      CALL FLUXSZ(FW,AK,HW,TMU,GZ,ZC,INDP,INDW,LLWALL,
     $            KG,KP,KH,NN,ANUV,SGK,PARAMK,IZCAL)
C
C ... 板境界処理は不要
C
CC      LL = 6+NN
CC      CALL FLUXPL(FU,FV,FW,LLWALP,LL)
C
C ... 新しい時刻のAKを計算する
C
      CALL ZERCLR(SRCA,MXYZ,0.0D0)
      CALL ZERCLR(SRCB,MXYZ,0.0D0)
C
      SRCB=GS+GT-EP
C
      CALL CLSNEW(AK,SN,FU,FV,FW,SRCA,SRCB,TMU,HH,
     $            XC,YC,ZC,XCP,YCOS,GV,GZ,
     $            INDP,INDU,INDV,KG,KP,KF,ANUV,SGK,0)
      CALL CHKVAL(AK,HH,HDEP,KF,AKMIN)
C
      RETURN
      END
