      SUBROUTINE BCGSTB(A,B,X,WK,NEQ,NEQEXT,IDSK,IDCG,INDOF,INDOP,MXITCG
     &                 ,CGTOL,IMPC,ITO)
C
      USE MPI_PARAM
C
      IMPLICIT REAL*8(A-H,O-Z)
C
      DIMENSION A(*),B(NEQ),X(NEQEXT),WK(NEQEXT,9),IDSK(NEQ+1),IDCG(*)
     *         ,INDOF(6,*),INDOP(*)
C
      MAXITR=MXITCG
      IF(MAXITR.EQ.0) THEN
        CALL CG_MPI_ALLREDUCE_I(NEQ,MAXITR,1,0)
        MAXITR=MAXITR/2
        IF(MAXITR.LT.50) MAXITR=50
      ENDIF
C
      CALL SCALUS(NEQ,WK(1,9),A,B,IDSK,IDCG,INDOF,INDOP,IMPC)
      CALL DTPRDCT(BNRM,B,B,NEQ)
      IF(BNRM.EQ.0.D0) THEN
        CALL CLEAR1(X,NEQ)
        RETURN
      ENDIF
      TOL=CGTOL*CGTOL*BNRM
      CALL CG3ILU2(WK(1,7),A,B,NEQ,IDSK,IDCG,ITO)
      CALL SHIFT1(WK(1,1),B,NEQ)
      CALL SHIFT1(WK(1,2),WK(1,1),NEQ)
      CALL SHIFT1(WK(1,3),WK(1,1),NEQ)
      CALL DTPRDCT(C1,WK(1,1),WK(1,2),NEQ)
      CALL CLEAR1(X,NEQ)
C
      DO 100 ITER=1,MAXITR
        CALL SHIFT1(WK(1,8),WK(1,3),NEQ)
        CALL CG3FWB2(WK(1,7),A,WK(1,8),NEQ,IDSK,IDCG,ITO)
        CALL CG3ML3(WK(1,6),A,WK(1,8),NEQ,IDSK,IDCG,INDOF,INDOP,IMPC
     &             ,ITO)
        CALL DTPRDCT(C2,WK(1,1),WK(1,6),NEQ)
        ALP=C1/C2
        CALL RMULT4(WK(1,4),WK(1,2),-ALP,WK(1,6),NEQ)
        CALL SHIFT1(WK(1,8),WK(1,4),NEQ)
        CALL CG3FWB2(WK(1,7),A,WK(1,8),NEQ,IDSK,IDCG,ITO)
        CALL CG3ML3(WK(1,5),A,WK(1,8),NEQ,IDSK,IDCG,INDOF,INDOP,IMPC
     &             ,ITO)
        CALL DTPRDCT(C31,WK(1,4),WK(1,5),NEQ)
        CALL DTPRDCT(C32,WK(1,5),WK(1,5),NEQ)
        C3=C31/C32
        CALL RMULT5(WK(1,8),ALP,WK(1,3),C3,WK(1,4),NEQ)
        CALL CG3FWB2(WK(1,7),A,WK(1,8),NEQ,IDSK,IDCG,ITO)
        CALL ADDVEC(X,X,WK(1,8),NEQ)
        CALL RMULT4(WK(1,2),WK(1,4),-C3,WK(1,5),NEQ)
C
        CALL DTPRDCT(RES,WK(1,2),WK(1,2),NEQ)
C
        IF( RES < TOL .OR. ( ITER == MAXITR .AND. RES < TOL*1.D3 ) )
     &    GOTO 200
C        
        CALL DTPRDCT(C1,WK(1,1),WK(1,2),NEQ)
        BETA=C1/(C2*C3)
        CALL RMULT4(WK(1,8),WK(1,3),-C3,WK(1,6),NEQ)
        CALL RMULT4(WK(1,3),WK(1,2),BETA,WK(1,8),NEQ)
  100 CONTINUE
C
      WRITE(ITO,*) 'NOT CONVERGED BY CG METHOD.'
      CALL ERRSTP(21,ITO)
C
  200 CALL VECML3(X,WK(1,9),X,NEQ)
C
      IF( NPROCS > 1 ) THEN
        CALL COMM_CG2(X,INDOF,INDOP)
        IF( IMPC > 0 ) CALL COMM_CG2X(X,INDOF,INDOP)
      ENDIF
C
      END        
