      SUBROUTINE PRNASE(NEQSOL,NALLOC,NREQ,LNUMI,LNUMO,NSIZ,ZFACT,ITO)
C
      IMPLICIT REAL*8(A-H,O-Z)
C
      INTEGER*8 NALLOC, NSIZ, NREQ
C
      WRITE(ITO,7439) 
 7439 FORMAT(/1X,5(1H*),2X,'MULTIFRONTAL SOLVER (ASE) MESSAGE',2X
     *       ,5(1H*) )
C
      WRITE(ITO,7449) NEQSOL, NALLOC*4.D-6, (NALLOC-NSIZ)*4.D-6, 
     *                NSIZ*4.D-6, NREQ*4.D-6 + LNUMI*8.D-6*ZFACT, 
     *                NREQ*4.D-6 + LNUMO*8.D-6*ZFACT
 7449 FORMAT(/3X,19HNUMBER OF EQUATIONS,1X,31(1H-),I8
     *       /3X,16HALLOCATED MEMORY,1X,34(1H-),F8.1,4H(MB)
     *       /3X,26HUSED MEMORY FOR DATA TABLE,1X,24(1H-),F8.1,4H(MB)
     *       /3X,34HAVAILABLE MEMORY FOR MATRIX SOLVER
     *       ,1X,16(1H-),F8.1,4H(MB)
     *       /3X,47HREQUIRED MEMORY FOR MATRIX SOLVER (INCORE ONLY)
     *       ,1X,3(1H-),F8.1,4H(MB)
     *       /3X,47HREQUIRED MEMORY FOR MATRIX SOLVER (OUTCORE USE)
     *       ,1X,3(1H-),F8.1,4H(MB) )
C
      RETURN
      END
