      SUBROUTINE STPRESS(PPND,NNOD,NPTIM,PTIM,PND,TIM)

      IMPLICIT REAL*8 (A-H,O-Z)
      DIMENSION PTIM(NPTIM),PND(NNOD,NPTIM),PPND(NNOD)

      CALL FINDINT(IS,IE,FAC,PTIM,NPTIM,TIM)

      PPND(:) = ( 1.D0 - FAC ) * PND(:,IS) + FAC * PND(:,IE)

      END
