      SUBROUTINE DEALLOC(KK,ITO,ICHK)

      USE MPI_PARAM
      USE M_VAL
      USE M_PART

      INTEGER*8 MUSED

      DIMENSION KK(*)

      WRITE(ITO,'(/X,A,F8.1,A)')
     &  'SUB. DEALLOC    : ', MUSED()*4.D-6, '(MB) USED.'

      DEALLOCATE( ISUB )

      DEALLOCATE( RTIM )

      DEALLOCATE( IGCD )
      IF( ISTM == 0 .AND. ICHK == 0 ) DEALLOCATE( GRID )

      IF( ICHK == 0 ) DEALLOCATE( IELM )

      DEALLOCATE( RODA )

      DEALLOCATE( MAT )
      DEALLOCATE( AMAT )

      DEALLOCATE( ISPD )
      DEALLOCATE( NSPD )
      DEALLOCATE( SPCD )

      DEALLOCATE( LOAD )
      DEALLOCATE( SLOD )
      DEALLOCATE( SILD )
      DEALLOCATE( LILD )

      DEALLOCATE( IFC )
      DEALLOCATE( NFC )
      DEALLOCATE( FC )

      DEALLOCATE( IPL4 )
      DEALLOCATE( NPL4 )
      DEALLOCATE( PLD4 )

      DEALLOCATE( IGRV )
      DEALLOCATE( GRAV )

      DEALLOCATE( ISPA )
      DEALLOCATE( NSPA )

      DEALLOCATE( ISP1 )
      DEALLOCATE( NSP1 )

      DEALLOCATE( ISPC )
      DEALLOCATE( NSPC )
      DEALLOCATE( SPC )

      DEALLOCATE( IDLD )
      DEALLOCATE( SDLD )
      DEALLOCATE( SIDL )
      DEALLOCATE( LIDL )

      DEALLOCATE( ITD1 )
      DEALLOCATE( TBD1 )

      DEALLOCATE( ISTP )
      DEALLOCATE( NSTP )
      DEALLOCATE( DELT )

      DEALLOCATE( ITL1 )

      DEALLOCATE( NPEW )
      DEALLOCATE( NIMPW )
      DEALLOCATE( NEXPW )

      DEALLOCATE( IPEW )
      DEALLOCATE( IDXIMPW )
      DEALLOCATE( NODIMPW )
      DEALLOCATE( IDXEXPW )
      DEALLOCATE( NODEXPW )

      IF( KK(92) == 0 ) RETURN

      DEALLOCATE( ICPA )
      DEALLOCATE( NCPA )

      DEALLOCATE( ICPR )
      DEALLOCATE( NCPR )

      DEALLOCATE( CPR )

      DEALLOCATE( NCRG )

      IF( ICHK < 2 ) DEALLOCATE( IBEL )

      DEALLOCATE( IBTE )

      DEALLOCATE( IELG )

      DEALLOCATE( NIBT )

      DEALLOCATE( IEQ )
      DEALLOCATE( IBT )

      END
