      SUBROUTINE PART_SEND_TBLX(KK)

      USE M_VAL
      USE MPI_PARAM
      USE M_PART

      IMPLICIT REAL*8(A-H,O-Z)

      DIMENSION KK(*)

      NPECG = NPROCS - 1

      ALLOCATE( NN_EXTX(NPECG) )
      ALLOCATE( NODX(MAXVAL(NN_INT),NPECG) )

      DO IP = 1, NPECG
        CALL PART_SEND_TBLX1(KK,IP)
      ENDDO

      DEALLOCATE( RSLV0 )
      DEALLOCATE( IFRIC )
      DEALLOCATE( FRIC )
      DEALLOCATE( U0 )
      DEALLOCATE( RL0 )

      CALL PART_SEND_TBLX2(KK)

      DEALLOCATE( NN_EXTX )
      DEALLOCATE( NODX )

      END
