      SUBROUTINE C_MPI_ALLREDUCE_I(ISEND,IRECV,N)

      USE MPI_PARAM

      INCLUDE 'mpif.h'

      DIMENSION ISEND(N),IRECV(N)

      CALL MPI_ALLREDUCE(ISEND,IRECV,N,MPI_INTEGER,MPI_SUM,CPLWORLD
     &                  ,IERR)

      END
