      SUBROUTINE CG_MPI_ISEND_D(DSEND,N,IDEST,IREQ)

      USE MPI_PARAM

      IMPLICIT REAL*8(A-H,O-Z)

      INCLUDE 'mpif.h'

      DIMENSION DSEND(N)

      CALL MPI_ISEND(DSEND,N,MPI_DOUBLE_PRECISION,IDEST,0,CGWORLD,IREQ
     &              ,IERR)

      END
