      SUBROUTINE M_MPI_BCAST_D(DBUF,N)

      USE MPI_PARAM

      IMPLICIT REAL*8(A-H,O-Z)

      INCLUDE 'mpif.h'

      DIMENSION DBUF(N)

      CALL MPI_BCAST(DBUF,N,MPI_DOUBLE_PRECISION,0,MYWORLD,IERR)

      END
