      SUBROUTINE M_MPI_RECV_I(IRECV,N,ISRC)

      USE MPI_PARAM

      INCLUDE 'mpif.h'

      DIMENSION IRECV(N),ISTATUS(MPI_STATUS_SIZE)

      CALL MPI_RECV(IRECV,N,MPI_INTEGER,ISRC,1,MYWORLD,ISTATUS,IERR)

      END
