      SUBROUTINE M_MPI_SEND_D(DSEND,N,IDEST)

      USE MPI_PARAM

      IMPLICIT REAL*8(A-H,O-Z)

      INCLUDE 'mpif.h'

      DIMENSION DSEND(N)

      CALL MPI_SEND(DSEND,N,MPI_DOUBLE_PRECISION,IDEST,1,MYWORLD,IERR)

      END
