      SUBROUTINE RECV_SURF(KK,RR)

      USE MPI_PARAM
      USE M_VAL

      IMPLICIT REAL*8(A-H,O-Z)

      DIMENSION KK(*),RR(*)

      NNOD = KK(8)
      NIGSF = KK(94)

      IF( MYRANK == 0 ) THEN
        CALL C_MPI_RECV_D(WLEVEL,1,IROOTC)
        CALL C_MPI_RECV_D(ALEVEL,1,IROOTC)
        CALL C_MPI_RECV_I(NPFC,1,IROOTC)
      ELSE
        IF( MYRANK == 1 ) CALL M_MPI_SEND_I(11,1,0)  ! SEND IOP=11 TO GLB_COMM
        CALL M_MPI_BCAST_D(WLEVEL,1)
        CALL M_MPI_BCAST_D(ALEVEL,1)
        CALL M_MPI_RECV_I(NPFC,1,0)
      ENDIF

      RR(8) = WLEVEL
      RR(9) = ALEVEL

      KK(81) = NPFC

      ALLOCATE( IPFC(10,NPFC) )
      ALLOCATE( AFC(NPFC) )
      ALLOCATE( IPND(NNOD) )

      IF( MYRANK == 0 ) THEN
        CALL C_MPI_RECV_I(IPFC,10*NPFC,IROOTC)
        CALL C_MPI_RECV_D(AFC,NPFC,IROOTC)
        CALL C_MPI_RECV_I(IPND,NNOD,IROOTC)
      ELSE
        CALL M_MPI_RECV_I(IPFC,10*NPFC,0)
        CALL M_MPI_RECV_D(AFC,NPFC,0)
        CALL M_MPI_RECV_I(IPND,NNOD,0)
      ENDIF

      IF( ISTM == 0 ) RETURN

      IF( MYRANK == 0 ) ALLOCATE( IRF(NPFC) )
      ALLOCATE( IRND(NNOD) )

      IF( MYRANK == 0 ) THEN
        CALL C_MPI_RECV_I(IRF,NPFC,IROOTC)
        CALL C_MPI_RECV_I(IRND,NNOD,IROOTC)
      ELSE
        CALL M_MPI_RECV_I(IRND,NNOD,0)
      ENDIF

      ALLOCATE( IRMSH(6,NNOD) )
      ALLOCATE( RMSH(4,NNOD) )
      ALLOCATE( DELZ(NNOD) )
      ALLOCATE( SUMZ(NNOD+NIGSF) )

      END
