      SUBROUTINE SEND_CONT(I_BCT,NICRG,NNCRG,ICRG,ICSF,ICTB)

      USE MPI_PARAM

      IMPLICIT REAL*8(A-H,O-Z)

      DIMENSION ICRG(2,NICRG),ICSF(6,NNCRG),ICTB(NICRG,NICRG)

      INTEGER, POINTER :: ICRG2(:),ICSF2(:,:)

      IF( MYRANK == 0 ) THEN

        CALL C_MPI_SEND_I(I_BCT,1,IROOTC)

        IF( I_BCT == 0 ) RETURN

        ALLOCATE( ICRG2(NICRG) )
        ALLOCATE( ICSF2(5,NNCRG) )
        ICRG2(:) = ICRG(2,:)
        ICSF2(:,:) = ICSF(2:6,:)

        CALL C_MPI_SEND_I(NICRG,1,IROOTC)
        CALL C_MPI_SEND_I(NNCRG,1,IROOTC)

        CALL C_MPI_SEND_I(ICRG2,NICRG,IROOTC)
        CALL C_MPI_SEND_I(ICSF2,5*NNCRG,IROOTC)
        CALL C_MPI_SEND_I(ICTB,NICRG*NICRG,IROOTC)

        DEALLOCATE( ICRG2 )
        DEALLOCATE( ICSF2 )

      ELSEIF( MYRANK == 1 ) THEN

        CALL M_MPI_SEND_I(21,1,0)  ! SEND IOP=21 TO GLB_COMM

        CALL M_MPI_SEND_I(I_BCT,1,0)

      ENDIF

      END
