      SUBROUTINE CLMYEQ(Q2,Q2N,QL,QLN,UU,VV,WW,DKXX,DKXY,DKYY,DKM,DKH,
     $                  HU,HV,HW,HX,HDEP,KH,
     $                  RHOW,GV,GX,GY,GZ,XC,YC,ZC,XCP,YCOS,YCOSP,
     $                  HH,WX,WY,CD,INDU,INDV,INDW,INDP,
     $                  LLWALL,LLWALP,KF,KG,KP,
     $                  FU,FV,FW,SRCA,SRCB,Q2BCN,QLBCN)
C======================================================================
C     Mellor-Yamada2.5乱流モデルを解く
C======================================================================
      IMPLICIT NONE
C
      INCLUDE 'DOMAIN.h'
      INCLUDE 'CP_NESTBC.h'
      INCLUDE 'TIMEI.h'
C
      REAL(8),INTENT(INOUT)::Q2(MX,MY,MZ),Q2N(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::QL(MX,MY,MZ),QLN(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::UU(MX,MY,MZ),VV(MX,MY,MZ),WW(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::HU(MX,MY,MZ),HV(MX,MY,MZ),HW(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::DKXX(MX,MY,MZ),DKXY(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::DKYY(MX,MY,MZ),DKM(MX,MY,MZ),DKH(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::RHOW(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::XC(8,MX,MY),YC(8,MY),ZC(8,MZ)
      REAL(8),INTENT(IN)::XCP(8,MX,MY),YCOS(MY),YCOSP(MY)
      REAL(8),INTENT(INOUT)::GV(MX,MY,MZ),GX(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::GY(MX,MY,MZ),GZ(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::HH(MX,MY),HX(MX,MY),HDEP(MX,MY)
      REAL(8),INTENT(INOUT)::WX(MX,MY),WY(MX,MY),CD(MX,MY)
      INTEGER,INTENT(INOUT)::INDU(MX,MY,MZ),INDV(MX,MY,MZ)
      INTEGER,INTENT(INOUT)::INDW(MX,MY,MZ),INDP(MX,MY,MZ)
      INTEGER,INTENT(INOUT)::LLWALL(8,MLWALL),LLWALP(8,MLWALP)
      INTEGER,INTENT(INOUT)::KF(MX,MY),KG(MX,MY),KP(MX,MY),KH(MX,MY)
      REAL(8),INTENT(INOUT)::FU(MX,MY,MZ),FV(MX,MY,MZ),FW(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::SRCA(MX,MY,MZ),SRCB(MX,MY,MZ)
      REAL(8),INTENT(INOUT)::Q2BCN(NXY,MZ,4),QLBCN(NXY,MZ,4)
C     局所変数
      REAL(8)::DKQL(MX,MY,MZ),GSGT(MX,MY,MZ),Q3DB(MX,MY,MZ)
      REAL(8)::RQ(MX,MY,MZ),RL(MX,MY,MZ)
      REAL(8)::Q2SRF(MX,MY),QLSRF(MX,MY)
C
C
      CALL Q2QLGEN(Q2,QL,RQ,RL,UU,VV,GV,RHOW,DKM,DKH,DKQL,GSGT,
     $             Q3DB,HH,WX,WY,CD,Q2SRF,QLSRF,ZC,INDP,KF,KG)
C
      CALL CLQ2EQ(Q2,Q2N,RL,UU,VV,WW,DKXX,DKYY,DKQL,GSGT,Q3DB,
     $            HU,HV,HW,HX,HDEP,KH,
     $            Q2BCN,Q2SRF,XC,YC,ZC,XCP,YCOS,GV,GX,GY,GZ,HH,
     $            INDP,INDU,INDV,INDW,LLWALL,LLWALP,KF,KG,KP,
     $            FU,FV,FW,SRCA,SRCB)
C
      CALL CLQLEQ(QL,QLN,RL,UU,VV,WW,DKXX,DKYY,DKQL,GSGT,Q3DB,
     $            HU,HV,HW,HX,HDEP,KH,
     $            QLBCN,QLSRF,XC,YC,ZC,XCP,YCOS,GV,GX,GY,GZ,HH,
     $            INDP,INDU,INDV,INDW,LLWALL,LLWALP,KF,KG,KP,
     $            FU,FV,FW,SRCA,SRCB)
C
      CALL MODRQRL(Q2,QL,RQ,RL,INDP,KF)
C
      CALL CLKMKH(RQ,RL,UU,VV,WW,RHOW,XC,YC,ZC,XCP,INDU,INDV,INDW,
     $            INDP,KF,KP,KG,DKXX,DKYY,DKXY,DKM,DKH)
C
      RETURN
      END
