      SUBROUTINE MPCSET(KK,ITO)
C
      USE M_VAL
      USE MPC_WORK
C
      DIMENSION KK(*)
C-----------------------------------------------------------------------
      N4 = KK(8) + KK(28) + KK(94) + KK(108) + KK(31)
      NINDC = KK(95)
      IFMDL = KK(96)
      NINDCX = KK(103)
C      
      CALL MPCSIZE(NIDEP,NIRH,NINDC+NINDCX,ISLV,IVRQ,IEDQ,IFCQ)
C
      KK(87) = NIDEP
C
      IF( NIDEP > 0 ) THEN
C
        ALLOCATE( ISLVG(2,N4) )
        ALLOCATE( NS(NINDC+NINDCX) )
        ALLOCATE( NM(NINDC+NINDCX) )
C
        CALL WRKSIZE(NSIZ1,NSIZ2,NSIZ3,ISLVG,NS,NM,N4,NINDC+NINDCX,INDC
     &              ,IEDG,IELC,IELQ,IFCQ,IEDQ,IVRQ,ISLV)
C
        DEALLOCATE( ISLVG )
        DEALLOCATE( NS )
        DEALLOCATE( NM )
C
        ALLOCATE( ICORR(N4) )
C
        CALL MPCRANK(KK(86),IRANK,ICORR,N4,NINDC+NINDCX,INDC,IEDG,IELC
     &              ,IELQ,IFCQ,IEDQ,IVRQ,ISLV)
C
        DEALLOCATE( ICORR )
C
        ALLOCATE( IDEP(2,NIDEP) )
        ALLOCATE( CIDP(NIDEP) )
        ALLOCATE( IDX(2,NIDEP) )
        ALLOCATE( IRH(2,NIRH) )
        ALLOCATE( IFRH(NIRH) )
        ALLOCATE( CRH(NIRH) )
        ALLOCATE( INDP(2,NIRH) )
C
        CALL MPCPREB(IDEP,CIDP,IDX,IRH,IFRH,INDP,NINDP,NINDC+NINDCX
     &              ,NIDEP,NIRH,ISLV,INDC,IEDG,IELC,IELQ,IVRQ,IEDQ,IFCQ
     &              ,INDOF,POS,IFMDL,ITO)
C
        ALLOCATE( IDL(NIDEP) )
        ALLOCATE( ROWL(NIDEP+1) )
        ALLOCATE( ROWR(NIDEP+1) )
        ALLOCATE( COLL0(NSIZ1) )
        ALLOCATE( COLR0(NSIZ2) )
C
        CALL INITIDX(ROWL,COLL0,ROWR,COLR0,NSIZ_L,NSIZ_R,IDEP,IDX,IRH
     &              ,INDP,NIDEP,NINDP,ITO)
C
        ALLOCATE( COLL(NSIZ_L) )
        ALLOCATE( COLR(NSIZ_R) )
        COLL(:) = COLL0(1:NSIZ_L)
        COLR(:) = COLR0(1:NSIZ_R)
        DEALLOCATE( COLL0 )
        DEALLOCATE( COLR0 )
C
        ALLOCATE( RWL2(NIDEP+1) )
        ALLOCATE( CLL20(NSIZ1) )
C
        CALL LHSIDX(NIDEP,ROWL,COLL,RWL2,CLL20,NSIZ_L2,IDL)
C
        ALLOCATE( CLL2(NSIZ_L2) )
        CLL2(:) = CLL20(1:NSIZ_L2)
        DEALLOCATE( CLL20 )
        DEALLOCATE( COLL )
C
        ALLOCATE( RWR2(NIDEP+1) )
        ALLOCATE( CLR20(NSIZ2) )
C
        CALL RHSIDXF(NIDEP,RWL2,CLL2,ROWR,COLR,RWR2,CLR20,NSIZ_R2)
C
        ALLOCATE( CLR2(NSIZ_R2) )
        CLR2(:) = CLR20(1:NSIZ_R2)
        DEALLOCATE( CLR20 )
        DEALLOCATE( COLR )
C
        ALLOCATE( RWR3(NIDEP+1) )
        ALLOCATE( CLR30(NSIZ2) )
C
        CALL RHSIDXB(NIDEP,RWL2,CLL2,RWR2,CLR2,RWR3,CLR30,NSIZ_R3)
C
        ALLOCATE( CLR3(NSIZ_R3) )
        CLR3(:) = CLR30(1:NSIZ_R3)
        DEALLOCATE( CLR30 )
C
        ALLOCATE( RWR4(NIDEP+1) )
        ALLOCATE( CLR4(NSIZ_R3) )
C
        CALL RHSIDXR(NIDEP,RWR4,CLR4,RWR3,CLR3)
C
        NSIZ_L = NSIZ_L2
        NSIZ_R = NSIZ_R3 
C
        ALLOCATE( COLL(NSIZ_L) )
        ALLOCATE( COLR(NSIZ_R) )
C
        ROWL(:) = RWL2(:)
        ROWR(:) = RWR4(:)
        COLL(:) = CLL2(:)
        COLR(:) = CLR4(:)
C
        DEALLOCATE( RWL2 )
        DEALLOCATE( CLL2 )
        DEALLOCATE( RWR2 )
        DEALLOCATE( CLR2 )
        DEALLOCATE( RWR3 )
        DEALLOCATE( CLR3 )
        DEALLOCATE( RWR4 )
        DEALLOCATE( CLR4 )
C
        ALLOCATE( B(NSIZ_L) )
C
        ALLOCATE( MPCF(2,NSIZ_R) )
        ALLOCATE( RMPC(NSIZ_R) )
        ALLOCATE( IDWK(NSIZ3) )
C
      ENDIF
C
      CALL MPCSET2(KK,INDOF,INDMPC,MPCF,NIDEP,IDEP,INDP,ROWR,COLR,IELM
     &            ,KK(37),INDC,IELC,IEDG,IELQ,IFCQ,IEDQ,IVRQ,ISLV,IFRIC
     &            ,IDWK)
C
      IF( NIDEP > 0 ) THEN
        DEALLOCATE( INDP )
        DEALLOCATE( IDWK )
      ENDIF
C
      END
