      SUBROUTINE RMPCCAL(RMPC,NINDC,ISLV,INDC,IEDG,IELC,IVRQ,IEDQ,IFCQ
     &                  ,POS,ITO)

      USE MPC_WORK
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION ISLV(2,NINDC),POS(3,*),IELC(3,*),INDC(NINDC),IEDG(6,*)
     &         ,IVRQ(*),IEDQ(*),IFCQ(*),RMPC(*)

      NIDEP = SIZE(IDL)
      NSIZ_R = SIZE(COLR)

      CALL CRH2SET(CRH,NINDC,ISLV,INDC,IEDG,IELC,IVRQ,IEDQ,IFCQ,POS,IRH)

      B(:) = 0.
      RMPC(1:NSIZ_R) = 0.

      CALL MPCSLV(NIDEP,B,RMPC,IDL,ROWL,COLL,ROWR,COLR,CIDP,IDX,IFRH,CRH
     &           ,ITO)

      END
