
!
! がれき算定で用いるデータ
! (control.datから読み込んだ条件等)
!
      CHARACTER(64) :: AREAFILE,STRFILE,ENDFILE
      CHARACTER(8)  :: CMODEL
      INTEGER :: SEED
      INTEGER,PARAMETER:: MAXTBL=100
      INTEGER :: N_TBL
      REAL(8) :: TBL_INUND(MAXTBL) ! 浸水深
      REAL(8) :: TBL_PDST(MAXTBL)  ! 破壊確率
      INTEGER :: DIVX,DIVY
      REAL(8) :: RHOD,QD,HD
      REAL(8) :: RHOL
      REAL(8) :: G_INUND ! 発生タイミングの浸水基準値[m]
!
      COMMON /CONTROL_C/ AREAFILE,STRFILE,ENDFILE,CMODEL
      COMMON /CONTROL_I/ SEED,N_TBL,DIVX,DIVY
      COMMON /CONTROL_R/ TBL_INUND,TBL_PDST,RHOD,QD,HD,RHOL,G_INUND
