      INTEGER,PARAMETER :: NGRDSZ=10001
      REAL(8),PARAMETER :: REARTH=6.37D6
      REAL(8) :: XGRID(NGRDSZ),YGRID(NGRDSZ),ZGRID(NGRDSZ)
      INTEGER :: ICORDTYPE
      COMMON /GRID/ XGRID,YGRID,ZGRID,ICORDTYPE

