MODULE M_PART

  IMPLICIT NONE

  INTEGER, ALLOCATABLE :: NN_INT(:)
  INTEGER, ALLOCATABLE :: NN_EXT(:)
  INTEGER, ALLOCATABLE :: NE(:)
  INTEGER, ALLOCATABLE :: NPF(:)
  INTEGER, ALLOCATABLE :: NDZ(:)

  INTEGER, ALLOCATABLE :: NOD(:,:)
  INTEGER, ALLOCATABLE :: IEL(:,:)
  INTEGER, ALLOCATABLE :: IPF(:,:)
  INTEGER, ALLOCATABLE :: IDZ(:,:)

  INTEGER, ALLOCATABLE :: NPEW(:),NIMPW(:),NEXPW(:)

  INTEGER, ALLOCATABLE :: IPEW(:,:)
  INTEGER, ALLOCATABLE :: IDXIMPW(:,:,:)
  INTEGER, ALLOCATABLE :: NODIMPW(:,:)
  INTEGER, ALLOCATABLE :: IDXEXPW(:,:,:)
  INTEGER, ALLOCATABLE :: NODEXPW(:,:)

  INTEGER :: NPE,NIMP,NEXP

  INTEGER, ALLOCATABLE :: IPE(:)
  INTEGER, ALLOCATABLE :: IDXIMP(:,:)
  INTEGER, ALLOCATABLE :: NODIMP(:)
  INTEGER, ALLOCATABLE :: IDXEXP(:,:)
  INTEGER, ALLOCATABLE :: NODEXP(:)

  INTEGER, ALLOCATABLE :: NG(:)
  INTEGER, ALLOCATABLE :: NIEC(:)
  INTEGER, ALLOCATABLE :: NINC(:)
  INTEGER, ALLOCATABLE :: NIEG(:)
  INTEGER, ALLOCATABLE :: NIEQ(:)
  INTEGER, ALLOCATABLE :: NIBT(:)

  INTEGER, ALLOCATABLE :: NODG(:,:)
  INTEGER, ALLOCATABLE :: IEC(:,:)
  INTEGER, ALLOCATABLE :: INC(:,:)
  INTEGER, ALLOCATABLE :: IEG(:,:)
  INTEGER, ALLOCATABLE :: IEQ(:,:)
  INTEGER, ALLOCATABLE :: IBT(:,:)

  INTEGER, ALLOCATABLE :: NODP(:,:)
  INTEGER, ALLOCATABLE :: IELCP(:,:)
  INTEGER, ALLOCATABLE :: INDCP(:,:)
  INTEGER, ALLOCATABLE :: IEDGP(:,:)

  INTEGER, ALLOCATABLE :: NN_EXTC(:)
  INTEGER, ALLOCATABLE :: NGC(:)
  INTEGER, ALLOCATABLE :: NEC(:)

  INTEGER, ALLOCATABLE :: NODC(:,:)
  INTEGER, ALLOCATABLE :: NODGC(:,:)
  INTEGER, ALLOCATABLE :: IELMC(:,:)

  INTEGER, ALLOCATABLE :: NN_EXTX(:)

  INTEGER, ALLOCATABLE :: NODX(:,:)

  INTEGER :: NPIMPX,NIMPX

  INTEGER, ALLOCATABLE :: IPIMPX(:)
  INTEGER, ALLOCATABLE :: IDXIMPX(:,:)
  INTEGER, ALLOCATABLE :: NODIMPX(:)

  INTEGER :: NPEXPX,NEXPX

  INTEGER, ALLOCATABLE :: IPEXPX(:)
  INTEGER, ALLOCATABLE :: IDXEXPX(:,:)
  INTEGER, ALLOCATABLE :: NODEXPX(:)

END MODULE M_PART
