MODULE M_VAL

  IMPLICIT NONE

  ! --- DATA TABLE ---

  INTEGER, ALLOCATABLE :: ISUB(:,:)

  REAL(8), ALLOCATABLE :: RTIM(:)

  INTEGER, ALLOCATABLE :: ICRD(:)
  REAL(8), ALLOCATABLE :: CORD(:,:)

  INTEGER, ALLOCATABLE :: INDG(:)
  INTEGER, ALLOCATABLE :: IGCD(:)
  REAL(8), ALLOCATABLE :: GRID(:,:)

  INTEGER, ALLOCATABLE :: IELM(:,:)

  REAL(8), ALLOCATABLE :: THK(:)
  REAL(8), ALLOCATABLE :: RODA(:)
  REAL(8), ALLOCATABLE :: BARD(:,:)
  REAL(8), ALLOCATABLE :: BVEC(:,:)
  INTEGER, ALLOCATABLE :: JELS(:,:)
  REAL(8), ALLOCATABLE :: PELS(:,:)

  INTEGER, ALLOCATABLE :: MAT(:,:)
  REAL(8), ALLOCATABLE :: AMAT(:,:)

  INTEGER, ALLOCATABLE :: MATT(:,:)

  INTEGER, ALLOCATABLE :: ITM1(:)
  REAL(8), ALLOCATABLE :: TBM1(:,:)

  INTEGER, ALLOCATABLE :: ISPD(:,:)
  INTEGER, ALLOCATABLE :: NSPD(:,:)
  REAL(8), ALLOCATABLE :: SPCD(:,:)

  INTEGER, ALLOCATABLE :: LOAD(:,:)
  REAL(8), ALLOCATABLE :: SLOD(:)
  REAL(8), ALLOCATABLE :: SILD(:)
  INTEGER, ALLOCATABLE :: LILD(:)

  INTEGER, ALLOCATABLE :: IFC(:,:)
  INTEGER, ALLOCATABLE :: NFC(:,:)
  REAL(8), ALLOCATABLE :: FC(:,:)

  INTEGER, ALLOCATABLE :: IPL4(:,:)
  INTEGER, ALLOCATABLE :: NPL4(:,:)
  REAL(8), ALLOCATABLE :: PLD4(:,:)

  INTEGER, ALLOCATABLE :: IPL1(:,:)
  INTEGER, ALLOCATABLE :: NPL1(:)
  REAL(8), ALLOCATABLE :: PLD1(:,:)

  INTEGER, ALLOCATABLE :: IGRV(:)
  REAL(8), ALLOCATABLE :: GRAV(:,:)

  INTEGER, ALLOCATABLE :: IRFC(:,:)
  REAL(8), ALLOCATABLE :: RFRC(:,:)

  INTEGER, ALLOCATABLE :: ITMP(:)
  REAL(8), ALLOCATABLE :: TEMP(:,:)

  INTEGER, ALLOCATABLE :: ITP1(:)
  INTEGER, ALLOCATABLE :: ITPF(:,:)
  REAL(8), ALLOCATABLE :: TMP1(:,:,:)

  INTEGER, ALLOCATABLE :: ISPA(:,:)
  INTEGER, ALLOCATABLE :: NSPA(:)

  INTEGER, ALLOCATABLE :: ISP1(:,:)
  INTEGER, ALLOCATABLE :: NSP1(:,:)

  INTEGER, ALLOCATABLE :: ISPC(:,:)
  INTEGER, ALLOCATABLE :: NSPC(:,:)
  REAL(8), ALLOCATABLE :: SPC(:,:)

  INTEGER, ALLOCATABLE :: IMPA(:,:)
  INTEGER, ALLOCATABLE :: NMPA(:)

  INTEGER, ALLOCATABLE :: IMPC(:,:)
  INTEGER, ALLOCATABLE :: JMPC(:)
  INTEGER, ALLOCATABLE :: NMPC(:,:)
  REAL(8), ALLOCATABLE :: AMPC(:)

  INTEGER, ALLOCATABLE :: NEIG(:,:)

  INTEGER, ALLOCATABLE :: IFR1(:,:)
  REAL(8), ALLOCATABLE :: FRQ1(:,:)

  INTEGER, ALLOCATABLE :: IDLD(:,:)
  REAL(8), ALLOCATABLE :: SDLD(:)
  REAL(8), ALLOCATABLE :: SIDL(:)
  INTEGER, ALLOCATABLE :: LIDL(:)

  INTEGER, ALLOCATABLE :: IRL1(:,:)

  INTEGER, ALLOCATABLE :: LSEQ(:,:)

  INTEGER, ALLOCATABLE :: ITD1(:)
  REAL(8), ALLOCATABLE :: TBD1(:,:)

  INTEGER, ALLOCATABLE :: NLP(:,:)
  REAL(8), ALLOCATABLE :: RNLP(:,:)

  INTEGER, ALLOCATABLE :: ISTP(:,:)
  INTEGER, ALLOCATABLE :: NSTP(:,:)
  REAL(8), ALLOCATABLE :: DELT(:)

  INTEGER, ALLOCATABLE :: ITL1(:,:)

  INTEGER, ALLOCATABLE :: ICPA(:,:)
  INTEGER, ALLOCATABLE :: NCPA(:)

  INTEGER, ALLOCATABLE :: ICPR(:,:)
  INTEGER, ALLOCATABLE :: NCPR(:,:)

  REAL(8), ALLOCATABLE :: CPR(:,:)

  INTEGER, ALLOCATABLE :: ICRG(:,:)
  INTEGER, ALLOCATABLE :: NCRG(:,:)

  ! --- DISPLACEMENT, FORCE ---

  REAL(8), ALLOCATABLE :: UG1(:,:)
  REAL(8), ALLOCATABLE :: UG2(:,:)
  REAL(8), ALLOCATABLE :: UG3(:,:)
  REAL(8), ALLOCATABLE :: UGP(:,:)
  REAL(8), ALLOCATABLE :: DUG(:,:)
  REAL(8), ALLOCATABLE :: POS(:,:)
  REAL(8), ALLOCATABLE :: POSO(:,:)
  REAL(8), ALLOCATABLE :: VG0(:,:,:,:)
  REAL(8), ALLOCATABLE :: VG(:,:,:,:)
  REAL(8), ALLOCATABLE :: VGP(:,:,:,:)
  REAL(8), ALLOCATABLE :: FTO(:,:)
  REAL(8), ALLOCATABLE :: FTI(:,:)
  REAL(8), ALLOCATABLE :: FTID(:,:)
  REAL(8), ALLOCATABLE :: FCO(:,:,:)
  REAL(8), ALLOCATABLE :: FCK(:,:,:)
  REAL(8), ALLOCATABLE :: FCD(:,:,:)
  REAL(8), ALLOCATABLE :: FCM(:,:,:)
  REAL(8), ALLOCATABLE :: FCMD(:,:,:)
  REAL(8), ALLOCATABLE :: FCP(:,:,:)
  REAL(8), ALLOCATABLE :: RFCO(:,:)
  REAL(8), ALLOCATABLE :: RFCI(:,:)
  REAL(8), ALLOCATABLE :: FRCI(:,:)

  ! --- PRESSURE, FLUX ---

  REAL(8), ALLOCATABLE :: PPND(:)
  REAL(8), ALLOCATABLE :: PG1(:)
  REAL(8), ALLOCATABLE :: PG2(:)
  REAL(8), ALLOCATABLE :: PG3(:)
  REAL(8), ALLOCATABLE :: DPG(:)
  REAL(8), ALLOCATABLE :: FLO(:)
  REAL(8), ALLOCATABLE :: FLI(:)

  ! --- WORK ---

  REAL(8), ALLOCATABLE :: WRK1(:,:)
  REAL(8), ALLOCATABLE :: WRK2(:,:)
  REAL(8), ALLOCATABLE :: WRK3(:,:)

  ! --- TRANSIENT ---

  REAL(8), ALLOCATABLE :: D_T(:)
  INTEGER, ALLOCATABLE :: IOUT(:)

  ! --- RESTART ---

  INTEGER, ALLOCATABLE :: IROUT(:)

  ! --- NONLINEAR ---

  REAL(8), ALLOCATABLE :: DMT(:,:)
  REAL(8), ALLOCATABLE :: EPSG(:,:)
  REAL(8), ALLOCATABLE :: SIGG(:,:)

  INTEGER, ALLOCATABLE :: IST(:,:)
  REAL(8), ALLOCATABLE :: SIGY(:,:)

  ! --- CONTACT ---

  INTEGER, ALLOCATABLE :: ICSF(:,:)
  INTEGER, ALLOCATABLE :: ICBD(:)
  INTEGER, ALLOCATABLE :: IELC(:,:)
  INTEGER, ALLOCATABLE :: IELCB(:)
  INTEGER, ALLOCATABLE :: INDA0(:)
  INTEGER, ALLOCATABLE :: INDC0(:)
  INTEGER, ALLOCATABLE :: INDA(:)
  INTEGER, ALLOCATABLE :: INDC(:)
  INTEGER, ALLOCATABLE :: IEDA(:)
  INTEGER, ALLOCATABLE :: IEDG(:,:)
  INTEGER, ALLOCATABLE :: IEDGB(:)
  INTEGER, ALLOCATABLE :: IELA(:,:)
  INTEGER, ALLOCATABLE :: ICELA(:,:)
  INTEGER, ALLOCATABLE :: ICEL(:)
  INTEGER, ALLOCATABLE :: ICFCA(:,:)
  INTEGER, ALLOCATABLE :: ICFC(:)
  INTEGER, ALLOCATABLE :: ICEDA(:,:)
  INTEGER, ALLOCATABLE :: ICED(:)
  INTEGER, ALLOCATABLE :: INDCEA(:,:)
  INTEGER, ALLOCATABLE :: INDCE(:)
  INTEGER, ALLOCATABLE :: IGSFR(:,:)
  INTEGER, ALLOCATABLE :: IBEL(:)
  INTEGER, ALLOCATABLE :: IBTE(:,:)
  INTEGER, ALLOCATABLE :: IELQ(:,:)
  INTEGER, ALLOCATABLE :: IFCQ(:)
  INTEGER, ALLOCATABLE :: IEDQ(:)
  INTEGER, ALLOCATABLE :: IVRQ(:)
  REAL(8), ALLOCATABLE :: GELC(:)
  INTEGER, ALLOCATABLE :: IELG(:)
  INTEGER, ALLOCATABLE :: ICTB(:,:)
  INTEGER, ALLOCATABLE :: ISLV0(:,:)
  INTEGER, ALLOCATABLE :: ISLVP(:)
  REAL(8), ALLOCATABLE :: RSLV0(:,:)
  REAL(8), ALLOCATABLE :: PSLV(:,:,:)
  INTEGER, ALLOCATABLE :: ISLV(:,:)
  INTEGER, ALLOCATABLE :: ISLVO(:,:)
  REAL(8), ALLOCATABLE :: RSLV(:,:)
  INTEGER, ALLOCATABLE :: IRANK(:)
  REAL(8), ALLOCATABLE :: FRTB(:,:,:)
  REAL(8), ALLOCATABLE :: U0(:,:,:)
  REAL(8), ALLOCATABLE :: RL0(:,:)
  INTEGER, ALLOCATABLE :: IFRIC(:,:)
  INTEGER, ALLOCATABLE :: ISTICK(:)
  INTEGER, ALLOCATABLE :: ISTK(:,:,:)
  REAL(8), ALLOCATABLE :: FRIC(:,:)
  REAL(8), ALLOCATABLE :: EDML(:)

  ! --- CADMAS ---

  INTEGER, ALLOCATABLE :: IPFC(:,:)
  REAL(8), ALLOCATABLE :: AFC(:)
  INTEGER, ALLOCATABLE :: IPND(:)
  REAL(8), ALLOCATABLE :: PTIM(:)
  REAL(8), ALLOCATABLE :: PND(:,:)

  ! --- DARCY FLUX ---

  REAL(8), ALLOCATABLE :: VELG(:,:,:)
  REAL(8), ALLOCATABLE :: VELE(:,:)

  ! --- STM ---

  INTEGER, ALLOCATABLE :: IRF(:)
  INTEGER, ALLOCATABLE :: IRND(:)
  INTEGER, ALLOCATABLE :: IRMSH(:,:)
  REAL(8), ALLOCATABLE :: RMSH(:,:)
  REAL(8), ALLOCATABLE :: DELZ(:)
  REAL(8), ALLOCATABLE :: SUMZ(:)

  ! --- INDEX ---

  INTEGER, ALLOCATABLE :: INDOF0(:,:)
  INTEGER, ALLOCATABLE :: INDOF(:,:)
  INTEGER, ALLOCATABLE :: INDMPC(:,:,:)
  INTEGER, ALLOCATABLE :: MPCF(:,:)
  REAL(8), ALLOCATABLE :: RMPC(:)

  INTEGER, ALLOCATABLE :: INDOP0(:)
  INTEGER, ALLOCATABLE :: INDOP(:)

  ! --- MATRIX SOLVER ---

  REAL(8), ALLOCATABLE, TARGET :: RHV(:)
  REAL(8), ALLOCATABLE :: X(:)

  INTEGER, ALLOCATABLE :: IDSK(:)
  INTEGER, ALLOCATABLE, TARGET :: IDCG(:)

  REAL(8), ALLOCATABLE :: CGWK(:,:)
  REAL(8), ALLOCATABLE, TARGET :: STF(:)
  REAL(8), ALLOCATABLE :: LOW(:)

  INTEGER, ALLOCATABLE :: IASEWK(:)
  REAL(8), ALLOCATABLE :: ASEWK(:)
  INTEGER, ALLOCATABLE :: SYM(:)
  REAL(8), ALLOCATABLE :: NUM(:)

  INTEGER(8) :: PT(64)
  INTEGER :: IPARM(64)

  ! --- ENSIGHT ---

  INTEGER :: N_PART
  INTEGER, ALLOCATABLE :: NP_ENS(:)
  INTEGER, ALLOCATABLE :: IP_ENS(:)
  INTEGER, ALLOCATABLE :: NG_ENS(:)
  INTEGER, ALLOCATABLE :: IG_ENS(:,:)
  INTEGER, ALLOCATABLE :: NE_ENS(:,:)
  INTEGER, ALLOCATABLE :: IE_ENS(:,:)

  INTEGER, ALLOCATABLE :: NG_ENSW(:)
  INTEGER, ALLOCATABLE :: IG_ENSW(:,:)
  INTEGER, ALLOCATABLE :: NE_ENSW(:,:)
  INTEGER, ALLOCATABLE :: IE_ENSW(:,:)

END MODULE M_VAL
