      SUBROUTINE RD_CORD2R( ICRD, CORD, ICRDR, I_CORD, CHAR, ITI )
C
      IMPLICIT REAL*8 (A-H,O-Z)
      CHARACTER*80 CHAR
      DIMENSION CORD(9), ICRDR(*)
C
      ICRD = 2
C
      READ(CHAR,'(BN,8X,I8,8X,6F8.0)') ID, CORD(1:6)
      READ(ITI,'(BN,8X,3F8.0)') CORD(7:9)
C
      ICRDR(ID) = I_CORD
C
      END
