      SUBROUTINE BCTSET0(KK)

      USE M_VAL

      IMPLICIT REAL*8 (A-H,O-Z)
      DIMENSION KK(*)

      NICRG = KK(92)

      CALL M_MPI_RECV_I(ICTB,NICRG*NICRG,1)
      CALL M_MPI_RECV_D(FRTB,3*NICRG*NICRG,1)
      CALL M_MPI_RECV_I(KK(96),1,1)

      END