      SUBROUTINE ENS_GEOM0(KK,IFG,FLNAME,NLEN,ICHK)

      USE M_VAL

      CHARACTER*256 FLNAME

      DIMENSION KK(*)

      CALL ENS_GEOM(KK,IFG,FLNAME,NLEN,ICHK)

      DEALLOCATE( GRID )
      DEALLOCATE( IELM )

      IF( ICHK == 2 ) THEN
        IF( KK(92) > 0 ) DEALLOCATE( IBEL )
        IF( KK(81) > 0 ) DEALLOCATE( IPFC )
      ENDIF

      END
