      SUBROUTINE FEMAP_OUT0(KK,INDG,IFMP)

      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION KK(*),INDG(*)

      CALL BLK_S(450,IFMP)

      CALL FMP_OUS0(IOUT,IFMP)

      CALL BLK_E(IFMP)

      CALL BLK_S(1051,IFMP)

      CALL FMP_NODAL0(IOUT,INDG,KK(8),KK(81),KK(25),IFMP)

      CALL FMP_SOL0(IOUT,INDG,KK(8),IFMP)

      CALL FMP_ROD0(IOUT,KK(10),KK(14),IFMP)

      CALL FMP_BAR0(IOUT,KK(10)+KK(14),KK(16),IFMP)

      IF( KK(25) > 0 ) CALL FMP_SOIL0(IOUT,INDG,KK(8),IFMP)

      CALL BLK_E(IFMP)

      END
