      SUBROUTINE RECV_PRES0(KK)

      USE M_VAL
      USE MPI_PARAM

      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION KK(*)
      REAL(8), POINTER :: PRESS(:)

      NNOD = KK(8)
      NPFC = KK(81)

      CALL M_MPI_RECV_I(I_BCT,1,1)

      IF( I_BCT > 0 ) THEN

        ALLOCATE( AFC(NPFC) )
        ALLOCATE( IPND(NNOD) )

        CALL C_MPI_RECV_D(AFC,NPFC,IROOTC)
        CALL C_MPI_RECV_I(IPND,NNOD,IROOTC)

        CALL SCATTER_SURFACE(AFC,1)
        CALL SCATTER_NODAL_I(IPND,1)

        DEALLOCATE( AFC )
        DEALLOCATE( IPND )

      ENDIF

      ALLOCATE( PRESS(NNOD) )
      CALL C_MPI_RECV_D(PRESS,NNOD,IROOTC)
      CALL SCATTER_NODAL_D(PRESS,1)
      DEALLOCATE( PRESS )

      CALL C_MPI_RECV_D(TNEXT,1,IROOTC)
      CALL M_MPI_BCAST_D(TNEXT,1)

      IF( TNEXT == 0.D0 ) RETURN

      CALL M_MPI_RECV_D(TIM,1,1)
      CALL C_MPI_SEND_D(TIM,1,IROOTC)
      
      END
