      SUBROUTINE SEND_CONT0(KK)

      USE M_VAL
      USE MPI_PARAM

      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION KK(*)
      INTEGER, POINTER :: ICRG2(:),ICSF2(:,:)

      NICRG = KK(92)
      NNCRG = KK(93)

      CALL M_MPI_RECV_I(I_BCT,1,1)

      CALL C_MPI_SEND_I(I_BCT,1,IROOTC)

      IF( I_BCT == 0 ) RETURN

      ALLOCATE( ICRG2(NICRG) )
      ALLOCATE( ICSF2(5,NNCRG) )
      ICRG2(:) = ICRG(2,:)
      ICSF2(:,:) = ICSF(2:6,:)

      CALL C_MPI_SEND_I(NICRG,1,IROOTC)
      CALL C_MPI_SEND_I(NNCRG,1,IROOTC)

      CALL C_MPI_SEND_I(ICRG2,NICRG,IROOTC)
      CALL C_MPI_SEND_I(ICSF2,5*NNCRG,IROOTC)
      CALL C_MPI_SEND_I(ICTB,NICRG*NICRG,IROOTC)

      DEALLOCATE( ICRG2 )
      DEALLOCATE( ICSF2 )

      END
