      REAL(8) :: RSURF(3),RINLT(8,NINLSZ),ROUTLT(2,NOTFSZ)
      REAL(8) :: RWALL(5,NWLLSZ),RDWALT,RDWALC
      REAL(8) :: RTIDE(2,8,NOTFSZ),HTIDE(2,NOTFSZ),ROMEG(8),HTIDE0
      REAL(8) :: AWIND10,ALBEDO,AKEXT
      COMMON /BOUNDR/ RSURF,RINLT,ROUTLT,
     &                RWALL,RDWALT,RDWALC,
     &                RTIDE,HTIDE,ROMEG,HTIDE0,AWIND10,ALBEDO,AKEXT
