      INTEGER,PARAMETER :: NINLSZ=100, NOTFSZ=100, NWLLSZ=500
      INTEGER :: ISURF(3),NINLT,MINLT(NINLSZ),IINLT(8,NINLSZ)
      INTEGER :: NOUTLT,MOUTLT(NOTFSZ),IOUTLT(3,NOTFSZ)
      INTEGER :: NWALL,MWALL(3,NWLLSZ),IWALL(5,NWLLSZ)
      INTEGER :: MDWALV,MDWALT,IDWALT,IDWALC,NTIDE,IPFLG
      INTEGER :: NOVRLP(4),NSOMER(4),ILGLWL,ILGLWP,NBOT
      INTEGER :: LVPNAB,IVPNAB,LNTANG
      INTEGER :: LMODDEP
      COMMON /BOUNDI/ ISURF,NINLT,MINLT,IINLT,
     &                NOUTLT,MOUTLT,IOUTLT,
     &                NWALL,MWALL,IWALL,
     &                MDWALV,MDWALT,IDWALT,IDWALC,NTIDE,IPFLG,
     &                NOVRLP,NSOMER,ILGLWL,ILGLWP,NBOT,
     &                LVPNAB,IVPNAB,LNTANG,LMODDEP

