      INTEGER,PARAMETER :: MAXPE=1024
      INTEGER :: IDCON(7),IPECON(8,MAXPE),IDTABL(2,MAXPE)
      INTEGER :: NUMPE(2,0:MAXPE),NUMCOM(5,MAXPE)
      INTEGER :: NSIZEALL,NSIZE,NRANK
      CHARACTER(LEN=64) :: NMFILE(MAXPE)
      COMMON /CONNEC_I/ IDCON,IPECON,IDTABL,NUMPE,NUMCOM,
     &                  NSIZEALL,NSIZE,NRANK
      COMMON /CONNEC_C/ NMFILE
