      INTEGER :: MX,MY,MZ,MXM,MYM,MZM,MXYZ,MXY,NXYZ
      INTEGER :: MLWALL,MLWALL1,MLWALP,MLWALB,MLWALBX,MLOFL,MLOFLX
      COMMON /DOMAIN/ MX,MY,MZ,MXM,MYM,MZM,MXYZ,MXY,NXYZ,
     &                MLWALL,MLWALL1,MLWALP,MLWALB,MLWALBX,MLOFL,MLOFLX
