      INTEGER :: NB_SD,NB_SD_MAIN
      LOGICAL:: NOCALDM
      REAL(8):: OFF_INTERVAL,OFF_START,OFF_NEXT
      COMMON /DRIFT/ OFF_INTERVAL,OFF_START,OFF_NEXT,
     $               NB_SD,NB_SD_MAIN,NOCALDM
