      INTEGER,PARAMETER :: NGRDSZ=10001
      REAL(8),PARAMETER :: REARTH=6.37D6
      REAL(8),PARAMETER :: CEARTH=7.29212D-5
CCC      REAL(8),PARAMETER :: CEARTH=0.0D0
      REAL(8) :: XGRID(NGRDSZ),YGRID(NGRDSZ),ZGRID(NGRDSZ)
      REAL(8) :: XCEN,YCEN
      REAL(8) :: HLMT,XORG,YORG,REGION(4)
      INTEGER :: ICORDTYPE
      COMMON /GRID/ XGRID,YGRID,ZGRID,XORG,YORG,HLMT
     $             ,XCEN,YCEN,REGION,ICORDTYPE

