      INTEGER,PARAMETER :: NINTSZ=100
      INTEGER :: NHINIT,IHINIT(4,NINTSZ)
      REAL(8) :: UUINIT,VVINIT,WWINIT,AKINIT
      REAL(8) :: EPINIT,TTINIT,CCINIT
      REAL(8) :: HHINIT(NINTSZ)
      COMMON /INITLI/ NHINIT,IHINIT
      COMMON /INITLR/ UUINIT,VVINIT,WWINIT,AKINIT,
     &                EPINIT,TTINIT,CCINIT,
     &                HHINIT
