      REAL(8) :: GRAV,GM2S,GM2B,PARAMF,PARAMF2,PARAMV,PARAMV2
      REAL(8) :: PARAMT,PARAMT2,PARAMC,PARAMC2,PARAMK,PARAMK2
      REAL(8) :: PRT,SCT,CORI,CSMG,GXB,GLH,GZH
      REAL(8) :: EPSH,EPST,RIMP,FNVAL(NFNSIZ),AABB(4)
      REAL(8) :: HAIDA
      REAL(8) :: DKENNEDY,DKENN1,DKENN2,DKENN3,BETAIWA,SAFEBRKW
      REAL(8) :: CFALLW0,DFALLWN0,DFALLWT0
      REAL(8) :: DISPBETA,DISPLIM,DISPBCLIM
C
      COMMON /MODELR/ GRAV,GM2S,GM2B,PARAMF,PARAMF2,PARAMV,PARAMV2,
     $                PARAMT,PARAMT2,PARAMC,PARAMC2,PARAMK,PARAMK2,
     $                PRT,SCT,CORI,CSMG,GXB,GLH,GZH,
     $                EPSH,EPST,RIMP,FNVAL,AABB,
     $                HAIDA,
     $                DKENNEDY,DKENN1,DKENN2,DKENN3,BETAIWA,SAFEBRKW,
     $                CFALLW0,DFALLWN0,DFALLWT0,
     $                DISPBETA,DISPBCLIM,DISPLIM
