      INTEGER,PARAMETER :: NFNSIZ=100
      INTEGER :: ISW(5)
      INTEGER :: IFNTBL(4,NFNSIZ)
      INTEGER :: MLNS,LSURF,LTYPH,LTEMP,LCONC,LDENS,LTURB,NFN,
     $           IGM2S,IGM2B,ISEAWL,IHONMA,IAIDA,IBKSTP,IMVERT,
     $           LDISS,LSEDI,LBRKW,LAIR,IFALLW,JFALLW,LDISP,
     $           LSTOCDS
      COMMON /MODELI/ MLNS,LSURF,LTYPH,LTEMP,LCONC,LDENS,LTURB,ISW,
     $                NFN,IFNTBL,IGM2S,IGM2B,ISEAWL,IHONMA,IAIDA,
     $                IBKSTP,IMVERT,LDISS,LSEDI,LBRKW,LAIR,IFALLW,
     $                JFALLW,LDISP,
     $                LSTOCDS
