      REAL(8) :: RA1,RA2,RB1,RB2,RC1,RCC,RE1,RE2,RKAR
      REAL(8) :: PARAMQ,PARAMQ2,Q2MIN,RLMIN,QLMIN,TVSVMX
      COMMON /MYCNST/ RA1,RA2,RB1,RB2,RC1,RCC,RE1,RE2,RKAR,
     $                PARAMQ,PARAMQ2,Q2MIN,RLMIN,QLMIN,TVSVMX

