      INTEGER,PARAMETER :: NOBSSZ=600, NOBPSZ=700, NPRSSZ=700
      INTEGER,PARAMETER :: NFRCSZ=100, NSEASZ=1000
      INTEGER :: LOBST,NOBSS,NOBSP,NPORS,NFRIC,NSEA,LFOBS,NFOBS,LDPRS
      INTEGER :: IOBSS(6,NOBSSZ),IOBSP(7,NOBPSZ),IPORS(7,NPRSSZ)
      INTEGER :: IFRIC(6,NFRCSZ),ISEA(2,NSEASZ)
      COMMON /OBSTI/ LOBST,NOBSS,NOBSP,NPORS,NFRIC,NSEA,LFOBS,NFOBS,
     &               IOBSS,IOBSP,IPORS,
     &               IFRIC,ISEA,LDPRS
