      INTEGER,PARAMETER :: NPHYSZ=60, NRSTSZ=50, NOUTSZ=4000, NPNTSZ=750
      INTEGER,PARAMETER :: MAXFRAGL=20
      CHARACTER(8) :: CLIST(NPHYSZ),CGRPH(NPHYSZ),CHIST(NPHYSZ)
      INTEGER :: LREST,NREST,IREST0,IREST(NRSTSZ)
      INTEGER :: LLIST,NLIST,ILIST0,ILIST(NOUTSZ),MLIST,LISTT
      INTEGER :: NLSECT,ILSECT(2,NPNTSZ)
      INTEGER :: LGRPH,NGRPH,IGRPH0,IGRPH(NOUTSZ),MGRPH
      INTEGER :: LHIST,IHIST0,IHIST,MHIST
      INTEGER :: NHCELL,IHCELL(3,NPNTSZ)
      INTEGER :: NHCELLSUM,LHCELL(NPNTSZ)
      INTEGER :: LENDF,NENDF,IENDF0,IENDF(NOUTSZ)
      INTEGER :: IALFAFLOW,KENSAMODE
      INTEGER :: NFRAGL
      REAL(8) :: RREST(NRSTSZ),RLIST(NOUTSZ),RGRPH(NOUTSZ)
      REAL(8) :: RHIST0,RHIST
      REAL(8) :: RFILE(3)
      REAL(8) :: RENDF(NOUTSZ)
      REAL(8) :: ETIME,WTM1,WTM2
      REAL(8) :: DFRAGL(MAXFRAGL)
      COMMON /OUTPUC/ CLIST,CGRPH,CHIST
      COMMON /OUTPUI/ LREST,NREST,IREST0,IREST,
     &                LLIST,NLIST,ILIST0,ILIST,MLIST,LISTT,
     &                NLSECT,ILSECT,
     &                LGRPH,NGRPH,IGRPH0,IGRPH,MGRPH,
     &                LHIST,IHIST0,IHIST,MHIST,
     &                NHCELL,IHCELL,NHCELLSUM,LHCELL,
     $                LENDF,NENDF,IENDF0,IENDF,IALFAFLOW,KENSAMODE,
     $                NFRAGL
      COMMON /OUTPUR/ RREST,RLIST,RGRPH,
     &                RHIST0,RHIST,RFILE,RENDF,
     $                ETIME,WTM1,WTM2,DFRAGL
