      REAL(8) :: RHO,RHOA,ADRHO,AMUH,AMUV,CP,CNDH,CNDV
      REAL(8) :: ANUH,ANUV,ALPH,ALPV,DIFH,DIFV
      COMMON /PROPTY/ RHO,RHOA,ADRHO,AMUH,AMUV,CP,CNDH,CNDV,
     &                ANUH,ANUV,ALPH,ALPV,DIFH,DIFV
