      REAL(8) :: ZLIMSD
      REAL(8) :: SSAND,DSAND,GVSAND
      REAL(8) :: AEXSD
      REAL(8) :: DIFHSD,DIFVSD,SCTHSD,SCTVSD
      REAL(8) :: CMAXSD
      REAL(8) :: BEDINI
      REAL(8) :: TSOFFLN,TEOFFLN,DTOFFLN
      REAL(8) :: PARAMSD,PARAMSD2
      REAL(8) :: WSEDI,PSIC
      REAL(8) :: PHIS,KCMIN
      INTEGER :: MWEXSD,MCONCSD,MDIFSD,MSETSD,MUSTSD,MRGHSD,MSHLSD
      INTEGER :: IBEDINI,IBEDSTR
      INTEGER :: MFDBCKSD,MOFFLNSD,MBDSLP
      REAL(8),PARAMETER:: SDNU=1.0D-6 !土砂移動計算で用いる海水の動粘性係数
      REAL(8),PARAMETER:: SDKP=0.4D0  !土砂移動計算で用いるカルマン定数
      REAL(8),PARAMETER:: SDCK=0.2D0  !浮遊砂濃度の鉛直分布を推定する際に用いる未定乗数(藤井ら,2009)

      COMMON /SEDIMENTR/ ZLIMSD,SSAND,DSAND,GVSAND,
     $                   DIFHSD,DIFVSD,SCTHSD,SCTVSD,AEXSD,CMAXSD,
     $                   PARAMSD,PARAMSD2,BEDINI,WSEDI,PSIC,
     $                   TSOFFLN,TEOFFLN,DTOFFLN,PHIS,KCMIN
      COMMON /SEDIMENTI/ MWEXSD,MCONCSD,MDIFSD,MSETSD,MUSTSD,MRGHSD,
     $                   MSHLSD,IBEDINI,IBEDSTR,MFDBCKSD,MOFFLNSD,MBDSLP
