      REAL(8) :: TIME,DT,DTOLD,DTV,RSTART,REND
      REAL(8) :: DTCNST,DTSAFE,DTMIN,DTMAX,VELMAX
      COMMON /TIMER/ TIME,DT,DTOLD,DTV,RSTART,REND,
     &               DTCNST,DTSAFE,DTMIN,DTMAX,VELMAX
