      REAL(8) :: AKAR,TAA,CMU,SGK,SGE,SGT,TC1,TC2,TC3,TCE,AKMIN,EPMIN
      REAL(8) :: TVSMAX,TVSMIN
      COMMON /TURBR/ AKAR,TAA,CMU,SGK,SGE,SGT,TC1,TC2,TC3,TCE,
     $               AKMIN,EPMIN,TVSMAX,TVSMIN
