      INTEGER,PARAMETER :: NTYHSZ=300
      REAL(8) :: TX(NTYHSZ),TY(NTYHSZ),TP(NTYHSZ),TR(NTYHSZ)
      REAL(8) :: TU(NTYHSZ),TV(NTYHSZ),XLN,YLT,C1,C2
      COMMON /TYPHOR/ TX,TY,TP,TR,
     &                TU,TV,XLN,YLT,C1,C2
