      SUBROUTINE SF_POS_UPDATE1(IPND0,PRES0,DELZ0,IFIX0,GRID,POS,IPGRID
     &                         ,IPGRID0,IRGRID,IELM,IGNO,XX,YY,ZZ,NF,PP
     &                         ,DZ,LNDC,DT)

      IMPLICIT REAL*8(A-H,O-Z)

      INCLUDE 'VF_A0PRM.h'
      INCLUDE 'VF_ANUMBI.h'
      INCLUDE 'VF_APARAI.h'
      INCLUDE 'VF_ATIMER.h'
      INCLUDE 'SF_STRUCT.h'

      DIMENSION GRID(3,NNOD),POS(3,NNOD),IELM(24,NELM),IGNO(NNOD)
     &         ,XX(MAXG1,NUMI),YY(MAXG1,NUMJ),ZZ(MAXG1,NUMK)
     &         ,NF(NUMI,NUMJ,NUMK),PP(NUMI,NUMJ,NUMK),IPGRID(2,NNOD)
     &         ,IPGRID0(2,NNOD0),IPND0(NNOD0),PRES0(NNOD0),DZ(NUMI,NUMJ)
     &         ,LNDC(NUMI,NUMJ),IRGRID(NNOD),DELZ0(NNOD0),IFIX0(NNOD0)

      TNEXT = TNOW + DT

      IF( TNEXT > TSTR2 ) THEN

        IF( ICON == 1 .AND. MYRANK == 0 )
     &    CALL SF_GIPND(IPND0,IPGRID0,NNOD0)

        CALL SF_GPRES(PRES0,PP,IPGRID,IGNO,POS,ZZ,NF)

        IF( ISTM == 1 ) THEN
          CALL SF_GDPTH(DELZ0,DZ,LNDC,IRGRID,IGNO,POS,XX,YY)
          DZ(:,:) = 0.D0
          CALL SF_VOLCHK(IFIX0,IELM,IGNO,GRID,POS,XX,YY)
        ENDIF

      ENDIF

      END
