      SUBROUTINE SF_STM2(DT,DTO)

      USE VF_A2ARRAY
      USE SF_ARRAY

      IMPLICIT REAL*8(A-H,O-Z)

      CALL SF_DPTH_UPDATE(DZ,SUMZ,XX,YY,ZZ,UU,VV,FF,FX,FY,GGX,GGY,GGW
     &                   ,GGR,LNDC,NF,INDX,INDY,FLFU,FLFV,DT,DTO)
      CALL SF_STM_OBST(GGV,GGX,GGY,GGZ,GGW,GLV,GLX,GLY,GLZ,NF,INDC,INDX
     &                ,INDY,INDZ,KST,GGV_0,GGX_0,GGY_0,GGZ_0,XX,YY,ZZ
     &                ,CM0,SUMZ,2,WK01,DBUF,WK14,WK15,WK16,WK17,WK18
     &                ,WK19,WK20)
      CALL SF_ALLOC1()
      CALL SF_BC_RESET(INDB,INDBK,INDBE,INDBT,INDBC,BCU,BCV,BCW,BCP
     &                ,BCF,BCVI,BCK,BCE,BCT,BCTI,BCC,BCCI,GGX,GGY
     &                ,GGZ,GLX,GLY,GLZ,NF,INDX,INDY,INDZ,INDX0,INDY0
     &                ,INDZ0,INDB0,INDBK0,INDBE0,INDBT0,INDBC0,BCU0
     &                ,BCV0,BCW0,BCP0,BCF0,BCVI0,BCK0,BCE0,BCT0
     &                ,BCTI0,BCC0,BCCI0,XX,YY,ZZ,IELM,POS,DVEL)
      CALL SF_CINIT(XX,YY,ZZ,UU,VV,WW,PP,FF,FX,FY,FZ,ANU,GGV,GGX,GGY
     &             ,GGZ,BCU,BCV,BCW,BCP,BCF,BCVI,DMTBTT,DMTBZZ,DMTBHH
     &             ,DMTBUN,DMTBUT,DBUF,WK01,WK02,WK03,NF,INDX,INDY
     &             ,INDZ,INDB,INDS,IBUF,WK14,WK15,WK16,WK17,WK18,WK19
     &             ,WK20)

      END
