      SUBROUTINE SF_STM_OBST(GGV,GGX,GGY,GGZ,GGW,GLV,GLX,GLY,GLZ,NF
     &                      ,INDC,INDX,INDY,INDZ,KST,GGV_0,GGX_0,GGY_0
     &                      ,GGZ_0,XX,YY,ZZ,CM0,SUMZ,MODE,WK01,DBUF,NFP
     &                      ,INDXP,INDYP,INDZP,GGXP,GGYP,GGZP)

      IMPLICIT REAL*8(A-H,O-Z)

      INCLUDE 'VF_A0PRM.h'
      INCLUDE 'VF_ANUMBI.h'
      INCLUDE 'VF_APARAI.h'

      DIMENSION GGV(NUMI,NUMJ,NUMK),GGX(NUMI,NUMJ,NUMK)
     &         ,GGY(NUMI,NUMJ,NUMK),GGZ(NUMI,NUMJ,NUMK)
     &         ,GGW(NUMI,NUMJ,NUMK),GGV_0(NUMI,NUMJ,NUMK)
     &         ,GGX_0(NUMI,NUMJ,NUMK),GGY_0(NUMI,NUMJ,NUMK)
     &         ,GGZ_0(NUMI,NUMJ,NUMK),XX(MAXG1,NUMI),YY(MAXG1,NUMJ)
     &         ,ZZ(MAXG1,NUMK),WK01(NUMI,NUMJ,NUMK),INDX(NUMI,NUMJ,NUMK)
     &         ,INDY(NUMI,NUMJ,NUMK),INDZ(NUMI,NUMJ,NUMK)
     &         ,NF(NUMI,NUMJ,NUMK),GLV(NUMI,NUMJ,NUMK)
     &         ,GLX(NUMI,NUMJ,NUMK),GLY(NUMI,NUMJ,NUMK)
     &         ,GLZ(NUMI,NUMJ,NUMK),DBUF(NUMBUF*MAXBUF)
     &         ,CM0(NUMI,NUMJ,NUMK),INDC(NUMI,NUMJ,NUMK)
     &         ,INDXP(NUMI,NUMJ,NUMK),INDYP(NUMI,NUMJ,NUMK)
     &         ,INDZP(NUMI,NUMJ,NUMK),NFP(NUMI,NUMJ,NUMK)
     &         ,GGXP(NUMI,NUMJ,NUMK),GGYP(NUMI,NUMJ,NUMK)
     &         ,GGZP(NUMI,NUMJ,NUMK),KST(NUMI,NUMJ),SUMZ(NUMI,NUMJ)

      NFP = NF

      INDXP = INDX
      INDYP = INDY
      INDZP = INDZ

      GGXP = GGX
      GGYP = GGY
      GGZP = GGZ

      GGV = GGV_0
      GGX = GGX_0
      GGY = GGY_0
      GGZ = GGZ_0

      CALL SF_MDPORO_H(GGV,GGX,GGY,GGZ,GGW,KST,NF,INDC,ZZ,SUMZ,MODE
     &                ,WK01,DBUF)

      CALL SF_INDX_RESET(INDX,INDY,INDZ,NF,GGX,GGY,GGZ)

      CALL VF_CGLV(CM0,GGV,GLV,NF)
      
      CALL VF_CGLXYZ(XX,YY,ZZ,CM0,GGX,GGY,GGZ,GLX,GLY,GLZ,DBUF,NF,INDX
     &              ,INDY,INDZ)
      
      END
