      SUBROUTINE SF_STM0()

      USE VF_A2ARRAY

      IMPLICIT REAL*8(A-H,O-Z)

      INCLUDE 'VF_A0PRM.h'
      INCLUDE 'VF_AFILEI.h'
      INCLUDE 'VF_APARAI.h'
      INCLUDE 'SF_STRUCT.h'

      IF( MYRANK == 0 ) CALL SF_STM_C_MPI_SEND_I(IRETYP,1,IROOTSTM)
      CALL SF_ALLOC0()
      CALL SF_OBST_POR(GGV_0,GGV,NF,DBUF)
      CALL SF_MDPORO_H(GGV,GGX,GGY,GGZ,GGW,KST,NF,INDC,ZZ,SUMZ
     &                ,0,WK01,DBUF)

      END
